package in.ramanujan.translation.codeConverter.ast;

import in.ramanujan.translation.codeConverter.exception.CompilationException;
import java.util.*;
import java.util.regex.*;

/**
 * AstParser parses Python AST dump strings (generated by `python3 -m ast`) into Java AST node objects.
 * 
 * <p>This parser uses a line-by-line state machine approach to convert the textual AST representation
 * into a structured tree of Java objects that can be traversed and converted to RuleEngineInput.</p>
 * 
 * <h3>Python AST Dump Format</h3>
 * <p>Python's AST module outputs a nested structure like:</p>
 * <pre>
 * Module(
 *   body=[
 *     Assign(
 *       targets=[Name(id='x', ctx=Store())],
 *       value=Constant(value=5))],
 *   type_ignores=[])
 * </pre>
 * 
 * <h3>Supported Python Constructs</h3>
 * <ul>
 *   <li><b>Assignments:</b> x = 5, arr[0] = 10</li>
 *   <li><b>Augmented Assignments:</b> x += 1, y *= 2</li>
 *   <li><b>Binary Operations:</b> x + y, a * b - c</li>
 *   <li><b>Comparisons:</b> x &gt; 5, a == b, y &lt;= 10</li>
 *   <li><b>Control Flow:</b> if/else, while loops</li>
 *   <li><b>Functions:</b> def func(a, b): return a + b</li>
 *   <li><b>Arrays/Lists:</b> [1, 2, 3], arr[index]</li>
 *   <li><b>Function Calls:</b> func(x, y)</li>
 * </ul>
 * 
 * <h3>Usage Example</h3>
 * <pre>
 * PythonAstInvoker invoker = new PythonAstInvoker();
 * String pythonCode = "x = 5\ny = x + 10";
 * String astDump = invoker.invokeAst(pythonCode);
 * 
 * AstParser parser = new AstParser();
 * ModuleNode module = parser.parse(astDump);
 * 
 * // Traverse the AST
 * for (AstNode node : module.getBody()) {
 *     if (node instanceof AssignNode) {
 *         AssignNode assign = (AssignNode) node;
 *         // Process assignment...
 *     }
 * }
 * </pre>
 * 
 * @see ModuleNode
 * @see AssignNode
 * @see BinOpNode
 * @see IfNode
 * @see WhileNode
 */
public class AstParser {
    
    private String[] lines;
    private int currentLine;
    
    /**
     * Parses a Python AST dump string into a ModuleNode tree structure.
     * 
     * <p><b>Python Code Example:</b></p>
     * <pre>
     * x = 5
     * y = 10
     * z = x + y
     * </pre>
     * 
     * <p><b>AST Dump Input:</b></p>
     * <pre>
     * Module(
     *   body=[
     *     Assign(targets=[Name(id='x', ctx=Store())], value=Constant(value=5)),
     *     Assign(targets=[Name(id='y', ctx=Store())], value=Constant(value=10)),
     *     Assign(targets=[Name(id='z', ctx=Store())], 
     *            value=BinOp(left=Name(id='x', ctx=Load()), op=Add(), right=Name(id='y', ctx=Load())))],
     *   type_ignores=[])
     * </pre>
     * 
     * <p><b>Output:</b> A ModuleNode containing 3 AssignNode objects in its body list.</p>
     * 
     * @param astDump The complete AST dump string from Python's ast module
     * @return ModuleNode representing the root of the parsed AST tree
     * @throws CompilationException If the AST dump doesn't start with Module or has invalid format
     */
    public ModuleNode parse(String astDump) throws CompilationException {
        lines = astDump.split("\n");
        currentLine = 0;
        
        // First line should be "Module("
        String firstLine = lines[0].trim();
        if (!firstLine.startsWith("Module(")) {
            throw new CompilationException(null, null, 
                "Expected Module at root, got: " + firstLine);
        }
        
        ModuleNode module = new ModuleNode();
        currentLine = 1; // Skip "Module("
        
        // Parse body
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            if (line.startsWith("body=[")) {
                currentLine++;
                module.setBody(parseBodyList(true)); // true = parsing module body
                break;
            }
            currentLine++;
        }
        
        return module;
    }
    
    /**
     * Parses a list of statements within a body block (Module, If, While, FunctionDef).
     * 
     * <p><b>Example - If statement body:</b></p>
     * <pre>
     * if x > 5:
     *     y = 10
     *     z = 20
     * </pre>
     * 
     * <p><b>AST Fragment:</b></p>
     * <pre>
     * body=[
     *   Assign(targets=[Name(id='y', ctx=Store())], value=Constant(value=10)),
     *   Assign(targets=[Name(id='z', ctx=Store())], value=Constant(value=20))]
     * </pre>
     * 
     * @return List of AstNode objects representing statements in the body
     * @throws CompilationException If statement parsing fails
     */
    private List<AstNode> parseBodyList() throws CompilationException {
        return parseBodyList(false);
    }
    
    /**
     * Parses a list of statements within a body block with context awareness.
     * 
     * @param isModuleBody true if parsing the module's body, false for other contexts
     * @return List of AstNode objects representing statements in the body
     * @throws CompilationException If statement parsing fails
     */
    private List<AstNode> parseBodyList(boolean isModuleBody) throws CompilationException {
        List<AstNode> body = new ArrayList<>();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            // Check for end of body list - line starts with ] or is just ],
            if (line.startsWith("]") || line.equals("],") || line.equals("])") || line.equals("]),")) {
                currentLine++;
                break;
            }
            
            // Check for structural elements that indicate end of this body
            // For module body: type_ignores=[ signals end
            // For function/if/while body: orelse=[, decorator_list=[, type_params=[ signal end
            if (line.startsWith("orelse=[")) {
                break;
            }
            if (isModuleBody && line.startsWith("type_ignores=[")) {
                break;
            }
            if (!isModuleBody && (line.startsWith("decorator_list=[") || line.startsWith("type_params=["))) {
                break;
            }
            
            int lineBeforeParsing = currentLine;
            AstNode node = parseNode(line);
            if (node != null) {
                body.add(node);
            }
            
            // After parsing a node, check if the line that ended the node also closed the body list
            // This handles cases like: right=Constant(value=1)))]),
            // where the Assign ends with ]) or ]), which also closes the body
            // IMPORTANT: Only check this for non-module bodies (function/if/while bodies)
            // Module body should continue parsing until it sees explicit end markers
            boolean isNestedStructure = (node instanceof WhileNode) || 
                                         (node instanceof IfNode) || 
                                         (node instanceof FunctionDefNode);
            if (!isModuleBody && currentLine > lineBeforeParsing && currentLine > 0) {
                String lastConsumedLine = lines[currentLine - 1].trim();
                
                if (isNestedStructure) {
                    // For nested structures (While, If, FunctionDef), their closing line closes THEM.
                    // But if the line has MULTIPLE ]) patterns, it also closes the outer body.
                    // Pattern: ])]) or ])])] means: inner ]), outer ])
                    int bodyClosingCount = countBodyClosingPatterns(lastConsumedLine);
                    if (bodyClosingCount >= 2) {
                        // Multiple bodies are closed, including the outer one
                        break;
                    }
                } else {
                    // For simple statements, check if this line contains the pattern ]) which closes body and parent structure
                    // Look for pattern: )...]) at the end, meaning closing parens followed by ]
                    if (lineClosesBodyAndParent(lastConsumedLine)) {
                        break;
                    }
                }
            }
        }
        
        return body;
    }
    
    /**
     * Checks if a line closes both the body list and a parent structure.
     * This happens when a line ends with patterns like:
     * - "...)])," - closes body ] and parent ) - where ] closes the body list
     * - "...)])"  - closes body ] and parent )
     * - "...))]),"-closes inner ), body ], parent )
     * 
     * Key distinction:
     * - ])), means: args], Call), Expr), comma - body NOT closed
     * - )])], means: args], Call), Expr), body], parent) - body IS closed
     * 
     * The pattern we're looking for is ] that closes the body, followed by )
     * Not ] that closes an args list followed by ))
     */
    private boolean lineClosesBodyAndParent(String line) {
        // Look for ])] pattern - this closes body] then parent)
        // The key is finding ]...] pattern where second ] closes body
        // or ])], which is body] followed by ,
        
        // Check for ]) at end which closes body] and parent) 
        // But NOT ])), which is args], Call), Expr)
        if (line.endsWith("]),") || line.endsWith("])")) {
            // Count ) after the last ]
            int lastBracket = line.lastIndexOf(']');
            int parenCount = 0;
            for (int i = lastBracket + 1; i < line.length(); i++) {
                if (line.charAt(i) == ')') parenCount++;
            }
            // If only one ) after ], it's body] parent) - body closed
            // If two or more ) after ], it could be args] Call) Expr) - need to check more
            if (parenCount == 1) {
                return true;
            }
        }
        
        // Check for ])])  pattern - args], Call), body], parent)
        // or )])], pattern
        if (line.contains("])],") || line.contains("])])") || line.contains(")])]")) {
            return true;
        }
        
        return false;
    }
    
    /**
     * Counts the number of body-closing patterns in a line.
     * A body-closing pattern is ]) which closes a body ] and its parent structure ).
     * 
     * <p>Example: "right=Constant(value=1)))])])," contains:
     * - First ]): closes inner While body and While
     * - Second ]): closes outer FunctionDef body and FunctionDef
     * Result: 2
     * 
     * @param line The line to check
     * @return Number of ]) patterns that close body+parent structures
     */
    private int countBodyClosingPatterns(String line) {
        int count = 0;
        int index = 0;
        
        // Count occurrences of ]) pattern
        while ((index = line.indexOf("])", index)) != -1) {
            count++;
            index += 2; // Move past ]) to find next occurrence
        }
        
        return count;
    }
    
    /**
     * Skips a bracketed section like "decorator_list=[]," or "type_params=[])".
     * Handles both single-line and multi-line cases.
     * 
     * <p><b>Examples:</b></p>
     * <pre>
     * decorator_list=[],
     * decorator_list=[
     *   Name(id='decorator1')],
     * type_params=[])
     * </pre>
     */
    private void skipBracketedSection() {
        String line = lines[currentLine].trim();
        
        // Check if the section is complete on a single line (e.g., "decorator_list=[]," or "type_params=[])")
        int bracketStart = line.indexOf('[');
        if (bracketStart >= 0) {
            int depth = 0;
            for (int i = bracketStart; i < line.length(); i++) {
                if (line.charAt(i) == '[') depth++;
                else if (line.charAt(i) == ']') {
                    depth--;
                    if (depth == 0) {
                        // Found matching bracket on same line
                        currentLine++;
                        return;
                    }
                }
            }
        }
        
        // Multi-line section, consume until we find the closing ]
        currentLine++;
        int depth = 1;
        while (currentLine < lines.length && depth > 0) {
            line = lines[currentLine].trim();
            for (int i = 0; i < line.length(); i++) {
                if (line.charAt(i) == '[') depth++;
                else if (line.charAt(i) == ']') depth--;
            }
            currentLine++;
        }
    }
    
    /**
     * Routes a line to the appropriate node parser based on the node type.
     * 
     * <p>Recognized node types and their Python equivalents:</p>
     * <ul>
     *   <li><b>Assign:</b> x = 5</li>
     *   <li><b>AugAssign:</b> x += 1</li>
     *   <li><b>If:</b> if x > 5: ...</li>
     *   <li><b>While:</b> while x < 10: ...</li>
     *   <li><b>FunctionDef:</b> def func(): ...</li>
     *   <li><b>Expr:</b> print(x)  (expression statement)</li>
     *   <li><b>Return:</b> return x</li>
     * </ul>
     * 
     * @param line The current line containing the node type
     * @return Parsed AstNode or null if node type is unrecognized
     * @throws CompilationException If parsing the specific node type fails
     */
    private AstNode parseNode(String line) throws CompilationException {
        line = line.trim();
        
        if (line.startsWith("Assign(")) {
            return parseAssign();
        } else if (line.startsWith("AugAssign(")) {
            return parseAugAssign();
        } else if (line.startsWith("If(")) {
            return parseIf();
        } else if (line.startsWith("While(")) {
            return parseWhile();
        } else if (line.startsWith("FunctionDef(")) {
            return parseFunctionDef();
        } else if (line.startsWith("ClassDef(")) {
            return parseClassDef();
        } else if (line.startsWith("Expr(")) {
            return parseExpr();
        } else if (line.startsWith("Return(")) {
            return parseReturn();
        }
        
        currentLine++;
        return null;
    }
    
    /**
     * Parses an assignment statement.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * # Simple assignment
     * x = 5
     * 
     * # Multiple targets
     * a = b = 10
     * 
     * # Array assignment
     * arr[0] = 100
     * 
     * # Expression assignment
     * result = x + y * z
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * Assign(
     *   targets=[Name(id='x', ctx=Store())],
     *   value=Constant(value=5))
     * </pre>
     * 
     * <p><b>Result:</b> AssignNode with targets list and value node.</p>
     * 
     * @return AssignNode containing target(s) and value
     * @throws CompilationException If assignment structure is invalid
     */
    private AssignNode parseAssign() throws CompilationException {
        AssignNode assign = new AssignNode();
        currentLine++;
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("targets=[")) {
                // Check if targets are inline (e.g., "targets=[Name(...)]," on same line)
                if (line.contains("],")) {
                    // Parse inline targets
                    assign.setTargets(parseInlineTargets(line));
                    currentLine++;
                } else {
                    currentLine++;
                    assign.setTargets(parseTargetsList());
                }
            } else if (line.startsWith("value=")) {
                assign.setValue(parseValue(line));
                // Check if the value line ended the Assign node
                // The Assign is closed if the line ends with )), )) , )], or )]
                String valueLine = lines[currentLine - 1].trim();
                if (isAssignClosedOnLine(valueLine)) {
                    break;
                }
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return assign;
    }
    
    /**
     * Checks if an Assign node is closed on the given line.
     * The Assign is closed if the line ends with enough closing syntax.
     */
    private boolean isAssignClosedOnLine(String line) {
        // Check for patterns that close an Assign:
        // )), - closes Assign after single-depth value
        // )) - same without comma
        // )], - closes Assign AND the containing body list
        // )] - same without comma
        // ]), - closes body list ] then FunctionDef ) with comma
        // ]) - closes body list ] then FunctionDef )
        // )])], - closes Assign, body list, and more
        // )]))  - closes Assign in nested structure (e.g. ListComp)
        // )])), - closes Assign with ListComp inside
        return line.endsWith(")),") || line.endsWith("))") ||
               line.endsWith(")],") || line.endsWith(")]") ||
               line.endsWith("))],") || line.endsWith("))]") ||
               line.endsWith("]),") || line.endsWith("])") ||
               line.endsWith(")])),") || line.endsWith(")]))");
    }
    
    /**
     * Parses the list of assignment targets.
     * 
     * <p><b>Examples:</b></p>
     * <pre>
     * x = 5              # targets=[Name]
     * arr[0] = 10        # targets=[Subscript]
     * a = b = c = 0      # targets=[Name, Name, Name]
     * </pre>
     * 
     * @return List of target nodes (NameNode or SubscriptNode)
     * @throws CompilationException If target parsing fails
     */
    private List<AstNode> parseTargetsList() throws CompilationException {
        List<AstNode> targets = new ArrayList<>();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            // Check if we've reached the end of the targets list
            if (line.startsWith("]") || line.equals("],")) {
                currentLine++;
                break;
            }
            
            if (line.startsWith("Name(")) {
                targets.add(parseName());
                // Check if the previous line ended the list (e.g., "Name(...)],")
                // parseName already advanced currentLine, so check the line we just processed
                String prevLine = lines[currentLine - 1].trim();
                if (prevLine.endsWith("],")) {
                    break;
                }
            } else if (line.startsWith("Subscript(")) {
                currentLine++;  // Move past "Subscript(" line before calling parseSubscript
                targets.add(parseSubscript());
                // Check if the previous line ended the list
                String prevLine = lines[currentLine - 1].trim();
                if (prevLine.endsWith("],") || prevLine.endsWith("])")) {
                    break;
                }
            } else if (line.startsWith("Attribute(")) {
                currentLine++;  // Move past "Attribute(" line
                targets.add(parseAttribute());
                // Check if the previous line ended the list
                String prevLine = lines[currentLine - 1].trim();
                if (prevLine.endsWith("],") || prevLine.endsWith("])")) {
                    break;
                }
            } else {
                currentLine++;
            }
        }
        
        return targets;
    }
    
    /**
     * Parses inline targets from a line like "targets=[Name(id='x', ctx=Store())],".
     * @param line The line containing inline targets
     * @return List of parsed target nodes
     */
    private List<AstNode> parseInlineTargets(String line) throws CompilationException {
        List<AstNode> targets = new ArrayList<>();
        
        // Extract content between targets=[ and ],
        int start = line.indexOf("targets=[") + "targets=[".length();
        int end = line.lastIndexOf("]");
        if (end < start) return targets;
        
        String content = line.substring(start, end);
        
        // Parse Name nodes from the content
        int idx = 0;
        while (idx < content.length()) {
            int nameStart = content.indexOf("Name(", idx);
            if (nameStart < 0) break;
            
            // Find the matching close paren for Name(
            int depth = 0;
            int nameEnd = nameStart;
            for (int i = nameStart; i < content.length(); i++) {
                if (content.charAt(i) == '(') depth++;
                else if (content.charAt(i) == ')') {
                    depth--;
                    if (depth == 0) {
                        nameEnd = i + 1;
                        break;
                    }
                }
            }
            
            String nameContent = content.substring(nameStart, nameEnd);
            NameNode node = new NameNode();
            // Extract id from Name(id='x', ctx=...)
            java.util.regex.Matcher m = java.util.regex.Pattern.compile("id='([^']+)'").matcher(nameContent);
            if (m.find()) {
                node.setId(m.group(1));
            }
            targets.add(node);
            
            idx = nameEnd;
        }
        
        return targets;
    }
    
    /**
     * Parses a Name node representing a variable reference.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * x = 5           # Name(id='x', ctx=Store())  - assignment target
     * y = x + 1       # Name(id='x', ctx=Load())   - reading variable
     * arr = mylist    # Name(id='mylist', ctx=Load())
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * Name(id='variableName', ctx=Store())  # or ctx=Load()
     * </pre>
     * 
     * <p>Context types:</p>
     * <ul>
     *   <li><b>Store:</b> Variable is being assigned to</li>
     *   <li><b>Load:</b> Variable value is being read</li>
     * </ul>
     * 
     * @return NameNode with id and context
     * @throws CompilationException If name format is invalid
     */
    private NameNode parseName() throws CompilationException {
        NameNode name = new NameNode();
        String line = lines[currentLine].trim();
        
        // Extract id from "Name(id='varName', ctx=Store())"
        Pattern pattern = Pattern.compile("id='([^']+)'");
        Matcher matcher = pattern.matcher(line);
        if (matcher.find()) {
            name.setId(matcher.group(1));
        }
        
        if (line.contains("ctx=Store()")) {
            name.setCtx("Store");
        } else if (line.contains("ctx=Load()")) {
            name.setCtx("Load");
        }
        
        // Check if Name node is complete on this line
        // A complete Name(...) has balanced parentheses
        boolean isComplete = isNameComplete(line);
        
        if (!isComplete) {
            currentLine++;
            // Find closing paren for multi-line Name nodes
            while (currentLine < lines.length) {
                line = lines[currentLine].trim();
                if (line.contains("ctx=Store()")) {
                    name.setCtx("Store");
                } else if (line.contains("ctx=Load()")) {
                    name.setCtx("Load");
                }
                if (line.startsWith(")") || line.startsWith("),")) {
                    break;
                }
                currentLine++;
            }
        }
        currentLine++;
        return name;
    }
    
    /**
     * Checks if a Name(...) expression is complete (balanced parens) on the given line.
     */
    private boolean isNameComplete(String line) {
        int nameStart = line.indexOf("Name(");
        if (nameStart < 0) return false;
        
        int depth = 0;
        for (int i = nameStart; i < line.length(); i++) {
            if (line.charAt(i) == '(') depth++;
            else if (line.charAt(i) == ')') {
                depth--;
                if (depth == 0) return true;
            }
        }
        return false;
    }
    
    /**
     * Parses a value expression (right-hand side of assignments, conditions, etc.).
     * 
     * <p><b>Supported value types:</b></p>
     * <pre>
     * 5                    # Constant
     * x                    # Name
     * x + y                # BinOp
     * func(a, b)           # Call
     * [1, 2, 3]            # List
     * arr[0]               # Subscript
     * x > 5                # Compare
     * </pre>
     * 
     * @param line The line containing the value expression
     * @return Parsed value node (ConstantNode, NameNode, BinOpNode, etc.)
     * @throws CompilationException If value type is unrecognized
     */
    private AstNode parseValue(String line) throws CompilationException {
        if (line.contains("Constant(")) {
            return parseConstant(line);
        } else if (line.contains("BinOp(")) {
            // Check if BinOp is complete on this line (single-line format)
            // or if it spans multiple lines
            if (isSingleLineBinOp(line)) {
                return parseSingleLineBinOp(line);
            }
            currentLine++;
            return parseBinOp();
        } else if (line.contains("Attribute(")) {
            // Must check before Name( since Attribute contains Name in its value
            currentLine++;
            return parseAttribute();
        } else if (line.contains("Name(")) {
            // Name can be inline (e.g., "left=Name(id='a', ctx=Load()),")
            // or on its own line
            return parseNameFromLine(line);
        } else if (line.contains("Call(")) {
            currentLine++;
            return parseCall();
        } else if (line.contains("ListComp(")) {
            // ListComp must be checked before List( since ListComp contains "List"
            currentLine++;
            return parseListComp();
        } else if (line.contains("List(")) {
            currentLine++;
            return parseList();
        } else if (line.contains("Subscript(")) {
            currentLine++;
            return parseSubscript();
        } else if (line.contains("Compare(")) {
            currentLine++;
            return parseCompare();
        }
        
        currentLine++;
        return null;
    }
    
    /**
     * Checks if a BinOp is complete on a single line.
     */
    private boolean isSingleLineBinOp(String line) {
        // Count opening and closing parens after BinOp(
        int binOpStart = line.indexOf("BinOp(");
        if (binOpStart < 0) return false;
        
        int depth = 0;
        for (int i = binOpStart; i < line.length(); i++) {
            if (line.charAt(i) == '(') depth++;
            else if (line.charAt(i) == ')') {
                depth--;
                if (depth == 0) return true; // Found matching close paren
            }
        }
        return false;
    }
    
    /**
     * Parses a BinOp that's complete on a single line.
     */
    private BinOpNode parseSingleLineBinOp(String line) throws CompilationException {
        BinOpNode binOp = new BinOpNode();
        
        // Extract operator
        Pattern opPattern = Pattern.compile("op=([A-Za-z]+)\\(\\)");
        Matcher opMatcher = opPattern.matcher(line);
        if (opMatcher.find()) {
            binOp.setOp(opMatcher.group(1));
        }
        
        // Extract left operand
        int leftStart = line.indexOf("left=");
        if (leftStart >= 0) {
            String afterLeft = line.substring(leftStart + 5);
            if (afterLeft.startsWith("Name(")) {
                binOp.setLeft(parseNameFromLine(afterLeft));
            } else if (afterLeft.startsWith("Constant(")) {
                binOp.setLeft(parseConstant(afterLeft));
            }
        }
        
        // Extract right operand
        int rightStart = line.indexOf("right=");
        if (rightStart >= 0) {
            String afterRight = line.substring(rightStart + 6);
            if (afterRight.startsWith("Name(")) {
                binOp.setRight(parseNameFromLine(afterRight));
            } else if (afterRight.startsWith("Constant(")) {
                binOp.setRight(parseConstant(afterRight));
            }
        }
        
        currentLine++;
        return binOp;
    }
    
    /**
     * Parses a Name node from within a line (not necessarily at the start).
     * Used for inline Names like "left=Name(id='a', ctx=Load()),".
     */
    private NameNode parseNameFromLine(String line) throws CompilationException {
        NameNode name = new NameNode();
        
        // Extract id from the line containing Name(id='varName', ...)
        Pattern pattern = Pattern.compile("id='([^']+)'");
        Matcher matcher = pattern.matcher(line);
        if (matcher.find()) {
            name.setId(matcher.group(1));
        }
        
        if (line.contains("ctx=Store()")) {
            name.setCtx("Store");
        } else if (line.contains("ctx=Load()")) {
            name.setCtx("Load");
        }
        
        // If the Name is complete on this line, advance currentLine
        // Check if the line has a complete Name(...) by looking for matching parens
        int nameStart = line.indexOf("Name(");
        if (nameStart >= 0) {
            int depth = 0;
            boolean found = false;
            for (int i = nameStart; i < line.length(); i++) {
                if (line.charAt(i) == '(') depth++;
                else if (line.charAt(i) == ')') {
                    depth--;
                    if (depth == 0) {
                        found = true;
                        break;
                    }
                }
            }
            if (found) {
                currentLine++;
                return name;
            }
        }
        
        // Multi-line Name, continue reading
        currentLine++;
        while (currentLine < lines.length) {
            String nextLine = lines[currentLine].trim();
            if (nextLine.contains("ctx=Store()")) {
                name.setCtx("Store");
            } else if (nextLine.contains("ctx=Load()")) {
                name.setCtx("Load");
            }
            if (nextLine.startsWith(")") || nextLine.startsWith("),")) {
                currentLine++;
                break;
            }
            currentLine++;
        }
        
        return name;
    }
    
    /**
     * Parses a constant literal value.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * 42              # Constant(value=42)        - Integer
     * 3.14            # Constant(value=3.14)      - Double
     * "hello"         # Constant(value='hello')   - String
     * True            # Constant(value=True)      - Boolean
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * Constant(value=42)
     * Constant(value=3.14)
     * Constant(value='hello')
     * </pre>
     * 
     * @param line The line containing the constant value
     * @return ConstantNode with parsed value (Integer, Double, or String)
     */
    private ConstantNode parseConstant(String line) {
        ConstantNode constant = new ConstantNode();
        
        // Extract value from "Constant(value=123)" format
        // Look specifically for the pattern inside Constant(...)
        Pattern constantPattern = Pattern.compile("Constant\\(value=([^)]+)\\)");
        Matcher constantMatcher = constantPattern.matcher(line);
        
        String valueStr = null;
        if (constantMatcher.find()) {
            valueStr = constantMatcher.group(1).trim();
        } else {
            // Fallback: try simple value= pattern for cases like "value=123"
            Pattern simplePattern = Pattern.compile("value=([^),]+)");
            Matcher simpleMatcher = simplePattern.matcher(line);
            if (simpleMatcher.find()) {
                valueStr = simpleMatcher.group(1).trim();
            }
        }
        
        if (valueStr != null) {
            try {
                if (valueStr.contains(".")) {
                    constant.setValue(Double.parseDouble(valueStr));
                } else {
                    constant.setValue(Integer.parseInt(valueStr));
                }
            } catch (NumberFormatException e) {
                // String value - remove quotes
                constant.setValue(valueStr.replaceAll("'", "").replaceAll("\"", ""));
            }
        }
        
        currentLine++;
        return constant;
    }
    
    /**
     * Parses a binary operation.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * x + y              # BinOp(left=Name('x'), op=Add(), right=Name('y'))
     * a - b              # BinOp(left=Name('a'), op=Sub(), right=Name('b'))
     * 2 * 3              # BinOp(left=Constant(2), op=Mult(), right=Constant(3))
     * x / y              # BinOp(left=Name('x'), op=Div(), right=Name('y'))
     * a ** b             # BinOp(left=Name('a'), op=Pow(), right=Name('b'))
     * x % y              # BinOp(left=Name('x'), op=Mod(), right=Name('y'))
     * </pre>
     * 
     * <p><b>Complex expression:</b></p>
     * <pre>
     * result = x + y * z
     * # BinOp(
     * #   left=Name('x'),
     * #   op=Add(),
     * #   right=BinOp(left=Name('y'), op=Mult(), right=Name('z')))
     * </pre>
     * 
     * <p><b>Supported operators:</b> Add, Sub, Mult, Div, Mod, Pow, FloorDiv, LShift, RShift, BitOr, BitXor, BitAnd</p>
     * 
     * @return BinOpNode with left operand, operator, and right operand
     * @throws CompilationException If binary operation structure is invalid
     */
    private BinOpNode parseBinOp() throws CompilationException {
        BinOpNode binOp = new BinOpNode();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("left=")) {
                binOp.setLeft(parseValue(line));
                // If parseValue didn't advance, we need to do so
                // (Name parsing from line doesn't advance)
                if (currentLine < lines.length && lines[currentLine].trim().equals(line)) {
                    currentLine++;
                }
            } else if (line.startsWith("op=")) {
                binOp.setOp(extractOp(line));
                currentLine++;
            } else if (line.startsWith("right=")) {
                binOp.setRight(parseValue(line));
                // If parseValue didn't advance, we need to do so
                if (currentLine < lines.length && lines[currentLine].trim().equals(line)) {
                    currentLine++;
                }
                // After parsing right, BinOp is done
                break;
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return binOp;
    }
    
    /**
     * Checks if a BinOp is closed on the given line (has enough closing parens).
     */
    private boolean isBinOpClosedOnLine(String line) {
        // Count closing parens after the last significant content
        int closeCount = 0;
        for (int i = line.length() - 1; i >= 0; i--) {
            char c = line.charAt(i);
            if (c == ')') closeCount++;
            else if (c == '(') closeCount--;
            else if (c != ',' && c != ']' && c != ' ') break;
        }
        // If we have 2+ closing parens at the end, BinOp is likely closed
        return closeCount >= 2;
    }
    
    /**
     * Extracts operator name from AST line.
     * 
     * <p><b>Examples:</b></p>
     * <pre>
     * "op=Add()"    -> "Add"
     * "op=Sub()"    -> "Sub"
     * "op=Mult()"   -> "Mult"
     * </pre>
     * 
     * @param line The line containing the operator
     * @return Operator name as string (e.g., "Add", "Sub", "Mult")
     */
    private String extractOp(String line) {
        // Extract "Add()" -> "Add", "Sub()" -> "Sub", etc.
        Pattern pattern = Pattern.compile("op=([A-Za-z]+)\\(\\)");
        Matcher matcher = pattern.matcher(line);
        if (matcher.find()) {
            return matcher.group(1);
        }
        return "";
    }
    
    /**
     * Parses a comparison operation.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * x > 5              # Compare(left=Name('x'), ops=[Gt()], comparators=[Constant(5)])
     * a == b             # Compare(left=Name('a'), ops=[Eq()], comparators=[Name('b')])
     * y <= 10            # Compare(left=Name('y'), ops=[LtE()], comparators=[Constant(10)])
     * x != 0             # Compare(left=Name('x'), ops=[NotEq()], comparators=[Constant(0)])
     * 
     * # Chained comparison
     * 0 < x < 10         # Compare(left=Constant(0), ops=[Lt(), Lt()], 
     *                    #         comparators=[Name('x'), Constant(10)])
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * Compare(
     *   left=Name(id='x', ctx=Load()),
     *   ops=[Gt()],
     *   comparators=[Constant(value=5)])
     * </pre>
     * 
     * <p><b>Comparison operators:</b> Lt (&lt;), LtE (&lt;=), Gt (&gt;), GtE (&gt;=), Eq (==), NotEq (!=), Is, IsNot, In, NotIn</p>
     * 
     * @return CompareNode with left side, operators list, and comparators list
     * @throws CompilationException If comparison structure is invalid
     */
    private CompareNode parseCompare() throws CompilationException {
        CompareNode compare = new CompareNode();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("left=")) {
                compare.setLeft(parseValue(line));
                // If parseValue didn't advance (inline Name), we need to advance
                if (currentLine < lines.length && lines[currentLine].trim().equals(line)) {
                    currentLine++;
                }
            } else if (line.startsWith("ops=[")) {
                // Check if ops are inline (e.g., "ops=[Gt()],")
                if (line.contains("],")) {
                    compare.setOps(parseInlineOps(line));
                    currentLine++;
                } else {
                    currentLine++;
                    compare.setOps(parseOpsList());
                }
            } else if (line.startsWith("comparators=[")) {
                // Check if comparators are inline
                if (line.contains("]),") || line.endsWith("])")) {
                    compare.setComparators(parseInlineComparators(line));
                    currentLine++;
                    break; // Compare is definitely closed if comparators are inline with ])
                } else {
                    currentLine++;
                    compare.setComparators(parseComparatorsList());
                    // After parsing comparators, check if the Compare is closed
                    if (currentLine > 0) {
                        String prevLine = lines[currentLine - 1].trim();
                        if (prevLine.endsWith("]),") || prevLine.endsWith("])")) {
                            break;
                        }
                    }
                }
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return compare;
    }
    
    /**
     * Parses the list of comparison operators.
     * 
     * <p><b>Examples:</b></p>
     * <pre>
     * x > 5              # ops=[Gt()]
     * 0 < x < 10         # ops=[Lt(), Lt()]
     * </pre>
     * 
     * @return List of operator names (e.g., ["Lt", "Gt", "Eq"])
     */
    private List<String> parseOpsList() {
        List<String> ops = new ArrayList<>();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            // Check for end of ops list
            if (line.startsWith("]") || line.equals("],")) {
                currentLine++;
                break;
            }
            
            // Extract operator like "Lt()" -> "Lt", "Gt()" -> "Gt"
            // Handle cases like "Gt()]," where the list ends on the same line
            Pattern pattern = Pattern.compile("([A-Za-z]+)\\(\\)");
            Matcher matcher = pattern.matcher(line);
            if (matcher.find()) {
                ops.add(matcher.group(1));
            }
            
            // Check if this line ends the ops list
            if (line.endsWith("],")) {
                currentLine++;
                break;
            }
            
            currentLine++;
        }
        
        return ops;
    }
    
    /**
     * Parses inline ops from a line like "ops=[Gt()],".
     */
    private List<String> parseInlineOps(String line) {
        List<String> ops = new ArrayList<>();
        Pattern pattern = Pattern.compile("([A-Za-z]+)\\(\\)");
        Matcher matcher = pattern.matcher(line);
        while (matcher.find()) {
            String op = matcher.group(1);
            // Skip context types like Load(), Store(), Del()
            if (!op.equals("Load") && !op.equals("Store") && !op.equals("Del")) {
                ops.add(op);
            }
        }
        return ops;
    }
    
    /**
     * Parses inline comparators from a line like "comparators=[Constant(value=5)]),".
     */
    private List<AstNode> parseInlineComparators(String line) throws CompilationException {
        List<AstNode> comparators = new ArrayList<>();
        
        // Find Constant nodes
        Pattern constPattern = Pattern.compile("Constant\\(value=([^)]+)\\)");
        Matcher constMatcher = constPattern.matcher(line);
        while (constMatcher.find()) {
            ConstantNode node = new ConstantNode();
            node.setValue(constMatcher.group(1));
            comparators.add(node);
        }
        
        // Find Name nodes
        Pattern namePattern = Pattern.compile("Name\\(id='([^']+)'");
        Matcher nameMatcher = namePattern.matcher(line);
        while (nameMatcher.find()) {
            NameNode node = new NameNode();
            node.setId(nameMatcher.group(1));
            comparators.add(node);
        }
        
        return comparators;
    }
    
    /**
     * Parses the list of values being compared against.
     * 
     * <p><b>Examples:</b></p>
     * <pre>
     * x > 5              # comparators=[Constant(5)]
     * a == b             # comparators=[Name('b')]
     * 0 < x < 10         # comparators=[Name('x'), Constant(10)]
     * </pre>
     * 
     * @return List of comparator nodes
     * @throws CompilationException If comparator parsing fails
     */
    private List<AstNode> parseComparatorsList() throws CompilationException {
        List<AstNode> comparators = new ArrayList<>();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            // Check for end of comparators list
            if (line.startsWith("]") || line.equals("],") || line.equals("]),")) {
                currentLine++;
                break;
            }
            
            if (line.startsWith("Name(")) {
                comparators.add(parseName());
                // Check if the previous line ended the list
                String prevLine = lines[currentLine - 1].trim();
                if (prevLine.endsWith("]),") || prevLine.endsWith("]")) {
                    break;
                }
            } else if (line.startsWith("Constant(")) {
                comparators.add(parseConstant(line));
                // Check if the line ended the list
                if (line.endsWith("]),") || line.endsWith("])")) {
                    break;
                }
            } else {
                currentLine++;
            }
        }
        
        return comparators;
    }
    
    /**
     * Parses an if statement with optional else block.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * # Simple if
     * if x > 5:
     *     y = 10
     * 
     * # If-else
     * if x > 5:
     *     y = 10
     * else:
     *     y = 20
     * 
     * # If-elif-else
     * if x > 10:
     *     y = 1
     * elif x > 5:
     *     y = 2
     * else:
     *     y = 3
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * If(
     *   test=Compare(left=Name('x'), ops=[Gt()], comparators=[Constant(5)]),
     *   body=[
     *     Assign(targets=[Name('y')], value=Constant(10))],
     *   orelse=[
     *     Assign(targets=[Name('y')], value=Constant(20))])
     * </pre>
     * 
     * @return IfNode with test condition, body statements, and optional else statements
     * @throws CompilationException If if statement structure is invalid
     */
    private IfNode parseIf() throws CompilationException {
        IfNode ifNode = new IfNode();
        currentLine++;
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("test=")) {
                ifNode.setTest(parseValue(line));
            } else if (line.startsWith("body=[")) {
                currentLine++;
                ifNode.setBody(parseBodyList());
            } else if (line.startsWith("orelse=[")) {
                currentLine++;
                ifNode.setOrelse(parseBodyList());
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return ifNode;
    }
    
    /**
     * Parses a while loop.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * # Simple while loop
     * while x < 10:
     *     x = x + 1
     * 
     * # While with complex condition
     * while x > 0 and y < 100:
     *     x = x - 1
     *     y = y + 2
     * 
     * # While-else (else executes if loop completes normally)
     * while x < 10:
     *     x = x + 1
     * else:
     *     print("Done")
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * While(
     *   test=Compare(left=Name('x'), ops=[Lt()], comparators=[Constant(10)]),
     *   body=[
     *     AugAssign(target=Name('x'), op=Add(), value=Constant(1))],
     *   orelse=[])
     * </pre>
     * 
     * @return WhileNode with test condition, body statements, and optional else statements
     * @throws CompilationException If while loop structure is invalid
     */
    private WhileNode parseWhile() throws CompilationException {
        WhileNode whileNode = new WhileNode();
        currentLine++;
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("test=")) {
                whileNode.setTest(parseValue(line));
            } else if (line.startsWith("body=[")) {
                currentLine++;
                whileNode.setBody(parseBodyList());
                // Check if body parsing also closed the While (no orelse follows)
                // This happens when the line before currentLine ends with ]),
                // meaning body] and While) are closed
                if (currentLine > 0) {
                    String lastLine = lines[currentLine - 1].trim();
                    // Pattern ]), means body closed ] and While closed ) - no orelse
                    // But ])) means body closed, something else closed - might have orelse
                    if (lastLine.endsWith("]),") || lastLine.endsWith("])")) {
                        break;
                    }
                }
            } else if (line.startsWith("orelse=[")) {
                currentLine++;
                whileNode.setOrelse(parseBodyList());
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return whileNode;
    }
    
    /**
     * Counts the number of closing parens after the last ] in a line.
     */
    private int countClosingParensAfterLastBracket(String line) {
        int lastBracket = line.lastIndexOf(']');
        if (lastBracket < 0) return 0;
        int count = 0;
        for (int i = lastBracket + 1; i < line.length(); i++) {
            if (line.charAt(i) == ')') count++;
        }
        return count;
    }
    
    /**
     * Parses a function definition.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * # Simple function
     * def add(a, b):
     *     return a + b
     * 
     * # Function with multiple statements
     * def calculate(x, y, z):
     *     temp = x + y
     *     result = temp * z
     *     return result
     * 
     * # Function with no parameters
     * def greet():
     *     print("Hello")
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * FunctionDef(
     *   name='add',
     *   args=arguments(
     *     posonlyargs=[],
     *     args=[arg(arg='a'), arg(arg='b')],
     *     kwonlyargs=[],
     *     kw_defaults=[],
     *     defaults=[]),
     *   body=[
     *     Return(value=BinOp(left=Name('a'), op=Add(), right=Name('b')))],
     *   decorator_list=[])
     * </pre>
     * 
     * @return FunctionDefNode with name, arguments, and body statements
     * @throws CompilationException If function definition structure is invalid
     */
    private FunctionDefNode parseFunctionDef() throws CompilationException {
        FunctionDefNode funcDef = new FunctionDefNode();
        currentLine++; // Skip the "FunctionDef(" line
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("name='")) {
                // Extract name from line like "name='add',"
                Pattern namePattern = Pattern.compile("name='([^']+)'");
                Matcher nameMatcher = namePattern.matcher(line);
                if (nameMatcher.find()) {
                    funcDef.setName(nameMatcher.group(1));
                }
                currentLine++;
            } else if (line.startsWith("args=arguments(")) {
                funcDef.setArgs(parseArguments());
            } else if (line.startsWith("body=[")) {
                currentLine++;
                funcDef.setBody(parseBodyList());
                // After parsing body, check if the body parsing also closed the FunctionDef
                // This handles AST patterns like: body=[...])], where ]) closes body and FunctionDef
                if (currentLine > 0) {
                    String lastLine = lines[currentLine - 1].trim();
                    if (lineClosesBodyAndParent(lastLine)) {
                        break;
                    }
                }
            } else if (line.startsWith("decorator_list=[")) {
                // Skip decorator_list - we don't parse it but must consume it
                // Check if the FunctionDef closes on this line (e.g., "decorator_list=[])")
                if (isFunctionDefClosedOnLine(line)) {
                    currentLine++;
                    break;
                }
                skipBracketedSection();
            } else if (line.startsWith("type_params=[")) {
                // Skip type_params - we don't parse it but must consume it
                // Check if the FunctionDef closes on this line (e.g., "type_params=[])")
                if (isFunctionDefClosedOnLine(line)) {
                    currentLine++;
                    break;
                }
                skipBracketedSection();
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return funcDef;
    }

    /**
     * Parses an Attribute node, e.g. {@code self.name} or {@code obj.value}.
     *
     * <p><b>AST Format:</b></p>
     * <pre>
     * Attribute(
     *   value=Name(id='self', ctx=Load()),
     *   attr='name',
     *   ctx=Store())
     * </pre>
     *
     * @return AttributeNode with value, attr, and ctx fields set
     * @throws CompilationException If attribute structure is invalid
     */
    private AttributeNode parseAttribute() throws CompilationException {
        AttributeNode attr = new AttributeNode();

        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();

            if (line.startsWith("value=")) {
                attr.setValue(parseValue(line));
            } else if (line.startsWith("attr='")) {
                Pattern attrPattern = Pattern.compile("attr='([^']+)'");
                Matcher attrMatcher = attrPattern.matcher(line);
                if (attrMatcher.find()) {
                    attr.setAttr(attrMatcher.group(1));
                }
                currentLine++;
            } else if (line.startsWith("ctx=")) {
                // e.g. ctx=Store() or ctx=Load()
                Pattern ctxPattern = Pattern.compile("ctx=([A-Za-z]+)\\(\\)");
                Matcher ctxMatcher = ctxPattern.matcher(line);
                if (ctxMatcher.find()) {
                    attr.setCtx(ctxMatcher.group(1));
                }
                // Check closing patterns on this line
                if (isAttributeClosedOnLine(line)) {
                    currentLine++;
                    break;
                }
                currentLine++;
            } else if (line.equals(")") || line.startsWith("),") || line.startsWith(")]")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }

        return attr;
    }

    /**
     * Returns true when the ctx= line also closes the Attribute node.
     * This happens for patterns like:
     * <ul>
     *   <li>{@code ctx=Store())} – closes Attribute</li>
     *   <li>{@code ctx=Store()),} – closes Attribute with trailing comma</li>
     *   <li>{@code ctx=Store()],} – closes Attribute and surrounding list</li>
     *   <li>{@code ctx=Load())],} – closes Attribute and surrounding list</li>
     *   <li>{@code ctx=Load()))],} – closes Attribute, Return/BinOp, and body list</li>
     * </ul>
     */
    private boolean isAttributeClosedOnLine(String line) {
        // ctx=Store()) or ctx=Load())  → attribute closed (+ parent if more )'s)
        return line.contains("())") || line.contains("),") || line.contains(")]");
    }
    
    /**
     * Checks if a FunctionDef is closed on the given line.
     * This happens when the line ends with ]) or ]), indicating the bracketed section
     * and the FunctionDef closing paren are on the same line.
     * Note: ], (bracket + comma) does NOT close FunctionDef, only ]) (bracket + paren) does.
     */
    private boolean isFunctionDefClosedOnLine(String line) {
        // Look for pattern like "...[])" or "...])," at the end of line
        // Must have ] followed by ) - not just ] followed by ,
        // Also handle "...[])," + "]," for cases where body list also closes on the same line
        return line.endsWith("[])") || line.endsWith("[]),") ||
               line.endsWith("[])],") || line.endsWith("[])],)");
    }
    
    /**
     * Parses function arguments specification.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * def func():              # arguments(args=[])
     * def func(a):             # arguments(args=[arg('a')])
     * def func(a, b, c):       # arguments(args=[arg('a'), arg('b'), arg('c')])
     * </pre>
     * 
     * @return ArgumentsNode containing list of argument names
     */
    private ArgumentsNode parseArguments() {
        ArgumentsNode arguments = new ArgumentsNode();
        currentLine++;
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("args=[")) {
                // Check if args are inline (e.g., "args=[arg(arg='a'), arg(arg='b')],")
                // or if it also closes arguments() (e.g., "args=[arg(arg='a')]),")
                if (line.contains("]),") || line.contains("])")) {
                    // This line closes both args array and arguments()
                    arguments.setArgs(parseInlineArgs(line));
                    currentLine++;
                    break; // arguments() is closed on this line
                } else if (line.contains("],")) {
                    arguments.setArgs(parseInlineArgs(line));
                    currentLine++;
                } else {
                    currentLine++;
                    arguments.setArgs(parseArgsList());
                    // After parseArgsList returns, check if arguments() was also closed
                    // by looking at the previous line that parseArgsList ended on
                    if (currentLine > 0) {
                        String prevLine = lines[currentLine - 1].trim();
                        if (prevLine.endsWith("]),") || prevLine.endsWith("])")) {
                            break; // arguments() was closed
                        }
                    }
                }
            } else if (line.equals(")") || line.startsWith("),") || line.endsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return arguments;
    }
    
    /**
     * Parses inline arguments from a line like "args=[arg(arg='a'), arg(arg='b')],".
     */
    private List<ArgNode> parseInlineArgs(String line) {
        List<ArgNode> args = new ArrayList<>();
        Pattern pattern = Pattern.compile("arg\\(arg='([^']+)'\\)");
        Matcher matcher = pattern.matcher(line);
        while (matcher.find()) {
            ArgNode arg = new ArgNode();
            arg.setArg(matcher.group(1));
            args.add(arg);
        }
        return args;
    }
    
    /**
     * Parses the list of individual function arguments.
     * 
     * <p><b>Examples:</b></p>
     * <pre>
     * args=[arg(arg='a'), arg(arg='b')]
     * # Results in: [ArgNode(arg='a'), ArgNode(arg='b')]
     * </pre>
     * 
     * @return List of ArgNode objects
     */
    private List<ArgNode> parseArgsList() {
        List<ArgNode> args = new ArrayList<>();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            // Check for end of args list - handle various closing patterns
            // "]" - just closing bracket
            // "]," - closing bracket with comma
            // "])," - closing bracket, paren, comma (closes both args array and arguments())
            // "])" - closing bracket, paren (closes both args array and arguments())
            if (line.startsWith("]") || line.equals("],") || line.equals("]),") || line.equals("])")) {
                currentLine++;
                break;
            }
            
            if (line.startsWith("arg(arg='") || line.contains("arg(arg='")) {
                ArgNode arg = new ArgNode();
                Pattern pattern = Pattern.compile("arg='([^']+)'");
                Matcher matcher = pattern.matcher(line);
                if (matcher.find()) {
                    arg.setArg(matcher.group(1));
                }
                args.add(arg);
                
                // Check if this line ends the args list
                // Handle: "arg(arg='x')]," or "arg(arg='x')]),", "arg(arg='x')])"
                if (line.endsWith("],") || line.endsWith("]),") || line.endsWith("])")) {
                    currentLine++;
                    break;
                }
            }
            
            currentLine++;
        }
        
        return args;
    }
    
    /**
     * Parses a function call expression.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * result = add(x, y)           # Call(func=Name('add'), args=[Name('x'), Name('y')])
     * print("hello")               # Call(func=Name('print'), args=[Constant('hello')])
     * calculate(1, 2, 3)           # Call(func=Name('calculate'), args=[Constant(1), Constant(2), Constant(3)])
     * arr.append(5)                # Call(func=Attribute(value=Name('arr'), attr='append'), args=[Constant(5)])
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * Call(
     *   func=Name(id='add', ctx=Load()),
     *   args=[Name(id='x', ctx=Load()), Name(id='y', ctx=Load())],
     *   keywords=[])
     * </pre>
     * 
     * @return CallNode with function reference and argument list
     * @throws CompilationException If function call structure is invalid
     */
    private CallNode parseCall() throws CompilationException {
        CallNode call = new CallNode();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("func=")) {
                call.setFunc(parseValue(line));
                // If parseValue didn't advance (inline Name), we need to advance
                if (currentLine < lines.length && lines[currentLine].trim().equals(line)) {
                    currentLine++;
                }
            } else if (line.startsWith("args=[")) {
                // Check if args are inline
                if (line.contains("],")) {
                    call.setArgs(parseInlineCallArgs(line));
                    currentLine++;
                } else {
                    currentLine++;
                    call.setArgs(parseCallArgsList());
                    // Check if args parsing already consumed the Call close
                    if (currentLine > 0) {
                        String prevLine = lines[currentLine - 1].trim();
                        // If prev line ends with ]) or ])) patterns, the Call is closed
                        // ])),  - closes args ], Call ), Expr )
                        // ]),   - closes args ], Call )
                        // ])    - closes args ], Call ) (no comma)
                        // ]))   - closes args ], Call ), Expr ) (no comma)
                        // ])])  - closes args ], Call ), another ] and )
                        if (prevLine.endsWith("]),") || prevLine.endsWith("])") ||
                            prevLine.endsWith("])),") || prevLine.endsWith("]))") ||
                            prevLine.contains("])")) {
                            break;
                        }
                    }
                }
            } else if (line.startsWith("keywords=[")) {
                // Skip the keywords list (we don't parse it but must consume it properly)
                // Check if the Call closes on this line (e.g., "keywords=[])," or "keywords=[])")
                if (isCallClosedOnKeywordsLine(line)) {
                    currentLine++;
                    break;
                }
                // Multi-line keywords - skip until we find the closing bracket
                skipBracketedSection();
            } else if (line.equals(")") || line.startsWith("),")) {
                // Only match simple close patterns, not compound ones like )])),
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return call;
    }
    
    /**
     * Checks if a Call is closed on the keywords line.
     * This happens when the line ends with ]), or ]) indicating the keywords list
     * and the Call closing paren are on the same line.
     */
    private boolean isCallClosedOnKeywordsLine(String line) {
        // Look for pattern like "keywords=[])," or "keywords=[])" at the end
        // Also handle "keywords=[])),", "keywords=[]))" for nested cases
        return line.endsWith("[]),") || line.endsWith("[])") ||
               line.endsWith("[])),") || line.endsWith("[]))") ||
               line.endsWith("[])]),") || line.endsWith("[])])");
    }
    
    /**
     * Parses inline call arguments from a line like "args=[Name(id='x', ctx=Load()), Name(id='y', ctx=Load())],".
     */
    private List<AstNode> parseInlineCallArgs(String line) throws CompilationException {
        List<AstNode> args = new ArrayList<>();
        
        // Find Name nodes
        Pattern namePattern = Pattern.compile("Name\\(id='([^']+)'");
        Matcher nameMatcher = namePattern.matcher(line);
        while (nameMatcher.find()) {
            NameNode node = new NameNode();
            node.setId(nameMatcher.group(1));
            args.add(node);
        }
        
        // Find Constant nodes
        Pattern constPattern = Pattern.compile("Constant\\(value=([^)]+)\\)");
        Matcher constMatcher = constPattern.matcher(line);
        while (constMatcher.find()) {
            ConstantNode node = new ConstantNode();
            node.setValue(constMatcher.group(1));
            args.add(node);
        }
        
        return args;
    }
    
    /**
     * Parses the argument list for a function call.
     * 
     * <p><b>Examples:</b></p>
     * <pre>
     * func()              # args=[]
     * func(x)             # args=[Name('x')]
     * func(x, 5, y+z)     # args=[Name('x'), Constant(5), BinOp(...)]
     * </pre>
     * 
     * @return List of argument nodes
     * @throws CompilationException If argument parsing fails
     */
    private List<AstNode> parseCallArgsList() throws CompilationException {
        List<AstNode> args = new ArrayList<>();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            // Check for empty or simple end of args list - only if there's no content to parse
            if (line.startsWith("]") && !line.contains("Constant(") && !line.contains("Name(") && !line.contains("BinOp(") && !line.contains("Subscript(")) {
                currentLine++;
                break;
            }
            
            // Parse different expression types - check for actual content first
            if (line.contains("Name(") && !line.startsWith("]")) {
                // Check if Name is inline in this line (e.g., "Name(id='x')]),")
                if (line.startsWith("Name(")) {
                    args.add(parseName());
                } else {
                    // Name is after some prefix - extract it
                    args.add(parseNameFromLine(line));
                    currentLine++;
                }
                // Check if the list ended on this line
                String prevLine = lines[currentLine - 1].trim();
                // Check for various patterns that close the args list:
                // ],   - just closes args
                // ]),  - closes args ] and Call )
                // ])   - same without comma
                // ])), - closes args ], Call ), Expr )
                // ]))  - same without comma
                if (prevLine.endsWith("],") || prevLine.endsWith("]),") || prevLine.endsWith("])") ||
                    prevLine.endsWith("])),") || prevLine.endsWith("]))")) {
                    break;
                }
            } else if (line.contains("Constant(")) {
                args.add(parseConstant(line));
                // Check if the list ended on this line
                String prevLine = lines[currentLine - 1].trim();
                if (prevLine.endsWith("],") || prevLine.endsWith("]),") || prevLine.endsWith("])") ||
                    prevLine.endsWith("])),") || prevLine.endsWith("]))")) {
                    break;
                }
            } else if (line.startsWith("BinOp(")) {
                currentLine++;
                args.add(parseBinOp());
                String prevLine = lines[currentLine - 1].trim();
                if (prevLine.endsWith("],") || prevLine.endsWith("]),") || prevLine.endsWith("])") ||
                    prevLine.endsWith("])),") || prevLine.endsWith("]))")) {
                    break;
                }
            } else if (line.startsWith("Subscript(")) {
                currentLine++;
                args.add(parseSubscript());
                String prevLine = lines[currentLine - 1].trim();
                if (prevLine.endsWith("],") || prevLine.endsWith("]),") || prevLine.endsWith("])") ||
                    prevLine.endsWith("])),") || prevLine.endsWith("]))")) {
                    break;
                }
            } else {
                currentLine++;
            }
        }
        
        return args;
    }
    
    /**
     * Parses array/list subscript access.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * x = arr[0]              # Subscript(value=Name('arr'), slice=Constant(0), ctx=Load())
     * arr[i] = 10             # Subscript(value=Name('arr'), slice=Name('i'), ctx=Store())
     * matrix[i][j]            # Nested subscripts
     * arr[i+1]                # Subscript with expression: slice=BinOp(...)
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * Subscript(
     *   value=Name(id='arr', ctx=Load()),
     *   slice=Constant(value=0),
     *   ctx=Load())
     * </pre>
     * 
     * @return SubscriptNode with array reference, index, and context
     * @throws CompilationException If subscript structure is invalid
     */
    private SubscriptNode parseSubscript() throws CompilationException {
        SubscriptNode subscript = new SubscriptNode();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("value=")) {
                subscript.setValue(parseValue(line));
            } else if (line.startsWith("slice=")) {
                subscript.setSlice(parseValue(line));
            } else if (line.contains("ctx=Store()")) {
                subscript.setCtx("Store");
                currentLine++;
                // Check if this line also closes the Subscript
                // e.g., "ctx=Store())],", "ctx=Store())"
                if (line.endsWith(")],") || line.endsWith(")]") || line.endsWith("))") || line.endsWith(")),")) {
                    break;
                }
            } else if (line.contains("ctx=Load()")) {
                subscript.setCtx("Load");
                currentLine++;
                // Check if this line also closes the Subscript
                if (line.endsWith(")],") || line.endsWith(")]") || line.endsWith("))") || line.endsWith(")),")) {
                    break;
                }
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return subscript;
    }
    
    /**
     * Parses a list literal.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * arr = []                    # List(elts=[], ctx=Load())
     * arr = [1, 2, 3]             # List(elts=[Constant(1), Constant(2), Constant(3)], ctx=Load())
     * arr = [x, y, z]             # List(elts=[Name('x'), Name('y'), Name('z')], ctx=Load())
     * arr = [x+1, y*2]            # List(elts=[BinOp(...), BinOp(...)], ctx=Load())
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * List(
     *   elts=[Constant(value=1), Constant(value=2), Constant(value=3)],
     *   ctx=Load())
     * </pre>
     * 
     * @return ListNode with elements list
     * @throws CompilationException If list structure is invalid
     */
    private ListNode parseList() throws CompilationException {
        ListNode list = new ListNode();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("elts=[")) {
                // Check if elts are inline
                if (line.contains("],")) {
                    list.setElts(parseInlineElts(line));
                    currentLine++;
                } else {
                    currentLine++;
                    list.setElts(parseEltsList());
                }
            } else if (line.contains("ctx=Load()")) {
                list.setCtx("Load");
                currentLine++;
            } else if (line.equals(")") || line.startsWith("),") || line.endsWith(")),") || line.endsWith("))")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return list;
    }
    
    /**
     * Parses inline elements from a line like "elts=[Constant(value=1), Constant(value=2)],".
     */
    private List<AstNode> parseInlineElts(String line) throws CompilationException {
        List<AstNode> elts = new ArrayList<>();
        
        // Find Constant nodes
        Pattern constPattern = Pattern.compile("Constant\\(value=([^)]+)\\)");
        Matcher constMatcher = constPattern.matcher(line);
        while (constMatcher.find()) {
            ConstantNode node = new ConstantNode();
            node.setValue(constMatcher.group(1));
            elts.add(node);
        }
        
        // Find Name nodes
        Pattern namePattern = Pattern.compile("Name\\(id='([^']+)'");
        Matcher nameMatcher = namePattern.matcher(line);
        while (nameMatcher.find()) {
            NameNode node = new NameNode();
            node.setId(nameMatcher.group(1));
            elts.add(node);
        }
        
        return elts;
    }
    
    /**
     * Parses the elements of a list literal.
     * 
     * <p><b>Examples:</b></p>
     * <pre>
     * [1, 2, 3]              # elts=[Constant(1), Constant(2), Constant(3)]
     * [x, y]                 # elts=[Name('x'), Name('y')]
     * </pre>
     * 
     * @return List of element nodes
     * @throws CompilationException If element parsing fails
     */
    private List<AstNode> parseEltsList() throws CompilationException {
        List<AstNode> elts = new ArrayList<>();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("]")) {
                currentLine++;
                break;
            }
            
            AstNode elt = parseNode(line);
            if (elt != null) {
                elts.add(elt);
            }
        }
        
        return elts;
    }
    
    /**
     * Parses a list comprehension.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * [0 for _ in range(5)]          # ListComp(elt=Constant(0), generators=[comprehension(...)])
     * [x*2 for x in range(10)]       # ListComp(elt=BinOp(...), generators=[comprehension(...)])
     * [x for x in range(10) if x%2]  # ListComp with condition in comprehension
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * ListComp(
     *   elt=Constant(value=0),
     *   generators=[
     *     comprehension(
     *       target=Name(id='_', ctx=Store()),
     *       iter=Call(func=Name(id='range'), args=[Constant(value=5)]),
     *       ifs=[],
     *       is_async=0)])
     * </pre>
     * 
     * @return ListCompNode representing the list comprehension
     * @throws CompilationException If parsing fails
     */
    private ListCompNode parseListComp() throws CompilationException {
        ListCompNode listComp = new ListCompNode();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("elt=")) {
                // Parse the element expression
                listComp.setElt(parseValue(line));
                // If parseValue didn't advance (inline Constant/Name), we need to advance
                if (currentLine < lines.length && lines[currentLine].trim().equals(line)) {
                    currentLine++;
                }
            } else if (line.startsWith("generators=[")) {
                currentLine++;
                listComp.setGenerators(parseGeneratorsList());
                // Check if the generators parsing already consumed the ListComp close
                // This happens when a line like "is_async=0)])),", ends everything
                if (currentLine > 0) {
                    String prevLine = lines[currentLine - 1].trim();
                    // If prev line ends with )), or ])),, the ListComp is already closed
                    if (prevLine.endsWith(")),") || prevLine.endsWith("))") ||
                        prevLine.endsWith("])),") || prevLine.endsWith("]))")) {
                        break;
                    }
                }
            } else if (line.equals(")") || line.startsWith("),") || line.endsWith("])") || line.endsWith("]),")) {
                // End of ListComp - check for various closing patterns
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return listComp;
    }
    
    /**
     * Parses the generators list in a list comprehension.
     * 
     * @return List of ComprehensionNode objects
     * @throws CompilationException If parsing fails
     */
    private List<ComprehensionNode> parseGeneratorsList() throws CompilationException {
        List<ComprehensionNode> generators = new ArrayList<>();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("]") || line.equals("],") || line.equals("])") || line.equals("]),")) {
                currentLine++;
                break;
            }
            
            if (line.startsWith("comprehension(")) {
                currentLine++;
                generators.add(parseComprehension());
                // Check if the comprehension parsing already consumed the generators list close
                // This happens when a line like "is_async=0)])),", "is_async=0)])," ends both
                // the comprehension and the generators list
                if (currentLine > 0) {
                    String prevLine = lines[currentLine - 1].trim();
                    // If prev line ends with ])), or ]),, etc., the list is already closed
                    if (prevLine.endsWith("])),") || prevLine.endsWith("]),") || 
                        prevLine.endsWith("])") || prevLine.endsWith("]))")) {
                        break;
                    }
                }
            } else {
                currentLine++;
            }
        }
        
        return generators;
    }
    
    /**
     * Parses a comprehension clause.
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * comprehension(
     *   target=Name(id='_', ctx=Store()),
     *   iter=Call(func=Name(id='range'), args=[Constant(value=5)]),
     *   ifs=[],
     *   is_async=0)
     * </pre>
     * 
     * @return ComprehensionNode representing the comprehension clause
     * @throws CompilationException If parsing fails
     */
    private ComprehensionNode parseComprehension() throws CompilationException {
        ComprehensionNode comp = new ComprehensionNode();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("target=")) {
                // Parse target (usually a Name node)
                comp.setTarget(parseValue(line));
                // If parseValue didn't advance (inline Name), we need to advance
                if (currentLine < lines.length && lines[currentLine].trim().equals(line)) {
                    currentLine++;
                }
            } else if (line.startsWith("iter=")) {
                // Parse the iterable expression (usually a Call to range, etc.)
                comp.setIter(parseValue(line));
                // If parseValue didn't advance (inline value), we need to advance
                if (currentLine < lines.length && lines[currentLine].trim().equals(line)) {
                    currentLine++;
                }
            } else if (line.startsWith("ifs=[")) {
                // Parse the conditions list (usually empty)
                if (line.contains("],")) {
                    // Empty or inline ifs
                    currentLine++;
                } else {
                    currentLine++;
                    comp.setIfs(parseIfsList());
                }
            } else if (line.startsWith("is_async=")) {
                // Parse is_async flag
                Pattern pattern = Pattern.compile("is_async=(\\d+)");
                Matcher matcher = pattern.matcher(line);
                if (matcher.find()) {
                    comp.setIsAsync(Integer.parseInt(matcher.group(1)));
                }
                currentLine++;
                // Check if this line also closes the comprehension
                // e.g., "is_async=0)])),", "is_async=0)]),"
                if (line.endsWith(")])),") || line.endsWith(")]),") || line.endsWith(")])")  || line.endsWith("))")) {
                    break;
                }
            } else if (line.equals(")") || line.startsWith("),") || line.endsWith("])") || line.endsWith("]),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return comp;
    }
    
    /**
     * Parses the ifs list in a comprehension (for conditional comprehensions).
     * 
     * @return List of condition nodes
     * @throws CompilationException If parsing fails
     */
    private List<AstNode> parseIfsList() throws CompilationException {
        List<AstNode> ifs = new ArrayList<>();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("]") || line.equals("],")) {
                currentLine++;
                break;
            }
            
            AstNode ifNode = parseNode(line);
            if (ifNode != null) {
                ifs.add(ifNode);
            }
        }
        
        return ifs;
    }

    /**
     * Parses an expression statement.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * print(x)               # Expr(value=Call(func=Name('print'), args=[Name('x')]))
     * arr.append(5)          # Expr(value=Call(...))
     * x + y                  # Expr(value=BinOp(...))  (rarely used alone)
     * </pre>
     * 
     * <p>Expression statements are standalone expressions that are evaluated but their
     * result is not assigned to anything. Commonly used for function calls with side effects.</p>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * Expr(
     *   value=Call(func=Name('print'), args=[Name('x')]))
     * </pre>
     * 
     * @return ExprNode wrapping the expression value
     * @throws CompilationException If expression structure is invalid
     */
    private ExprNode parseExpr() throws CompilationException {
        ExprNode expr = new ExprNode();
        currentLine++;
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("value=")) {
                expr.setValue(parseValue(line));
                // Check if parseValue's Call consumed the Expr close
                if (currentLine > 0) {
                    String prevLine = lines[currentLine - 1].trim();
                    // Check for patterns that indicate Expr is closed:
                    // )),  - closes Call ), Expr )
                    // ))   - same without comma
                    // )])  - closes args ], Call ), Expr ) - when body closing follows
                    // ])]  - closes args ], Call ), Expr ), body ]
                    if (prevLine.endsWith(")),") || prevLine.endsWith("))") ||
                        prevLine.contains("])") || prevLine.contains(")]")) {
                        break;
                    }
                }
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return expr;
    }
    
    /**
     * Parses a return statement.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * return x               # Return(value=Name('x'))
     * return 42              # Return(value=Constant(42))
     * return x + y           # Return(value=BinOp(left=Name('x'), op=Add(), right=Name('y')))
     * return                 # Return(value=None)
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * Return(
     *   value=BinOp(
     *     left=Name(id='a', ctx=Load()),
     *     op=Add(),
     *     right=Name(id='b', ctx=Load())))
     * </pre>
     * 
     * @return ReturnNode with optional return value
     * @throws CompilationException If return statement structure is invalid
     */
    private ReturnNode parseReturn() throws CompilationException {
        ReturnNode returnNode = new ReturnNode();
        currentLine++;
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("value=")) {
                returnNode.setValue(parseValue(line));
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return returnNode;
    }
    
    /**
     * Parses an augmented assignment statement.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * x += 5                 # AugAssign(target=Name('x'), op=Add(), value=Constant(5))
     * y -= 3                 # AugAssign(target=Name('y'), op=Sub(), value=Constant(3))
     * z *= 2                 # AugAssign(target=Name('z'), op=Mult(), value=Constant(2))
     * count /= 10            # AugAssign(target=Name('count'), op=Div(), value=Constant(10))
     * arr[i] += 1            # AugAssign(target=Subscript(...), op=Add(), value=Constant(1))
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * AugAssign(
     *   target=Name(id='x', ctx=Store()),
     *   op=Add(),
     *   value=Constant(value=5))
     * </pre>
     * 
     * <p>Augmented assignments combine an operation with assignment:</p>
     * <ul>
     *   <li>x += y  is equivalent to  x = x + y</li>
     *   <li>x *= y  is equivalent to  x = x * y</li>
     *   <li>x -= y  is equivalent to  x = x - y</li>
     * </ul>
     * 
     * @return AugAssignNode with target, operator, and value
     * @throws CompilationException If augmented assignment structure is invalid
     */
    private AugAssignNode parseAugAssign() throws CompilationException {
        AugAssignNode augAssign = new AugAssignNode();
        currentLine++;
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("target=")) {
                augAssign.setTarget(parseValue(line));
            } else if (line.startsWith("op=")) {
                augAssign.setOp(extractOp(line));
                currentLine++;
            } else if (line.startsWith("value=")) {
                augAssign.setValue(parseValue(line));
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return augAssign;
    }

    /**
     * Parses a class definition statement.
     *
     * <p><b>Python Example:</b></p>
     * <pre>
     * class Person:
     *     def __init__(self, name):
     *         self.name = name
     * </pre>
     *
     * <p><b>AST Format (abbreviated):</b></p>
     * <pre>
     * ClassDef(
     *   name='Person',
     *   bases=[],
     *   keywords=[],
     *   body=[
     *     FunctionDef(name='__init__', ...)],
     *   decorator_list=[])
     * </pre>
     *
     * @return ClassDefNode with name, bases, and body
     * @throws CompilationException If class definition structure is invalid
     */
    private ClassDefNode parseClassDef() throws CompilationException {
        ClassDefNode classDef = new ClassDefNode();
        currentLine++; // skip "ClassDef(" line

        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();

            if (line.startsWith("name='")) {
                Pattern namePattern = Pattern.compile("name='([^']+)'");
                Matcher nameMatcher = namePattern.matcher(line);
                if (nameMatcher.find()) {
                    classDef.setName(nameMatcher.group(1));
                }
                currentLine++;
            } else if (line.startsWith("bases=[")) {
                // Skip bases section (inheritance); consume but do not parse
                if (line.contains("],") || line.endsWith("]")) {
                    currentLine++;
                } else {
                    skipBracketedSection();
                }
            } else if (line.startsWith("keywords=[")) {
                // Skip keywords
                if (line.contains("],") || line.endsWith("]")) {
                    currentLine++;
                } else {
                    skipBracketedSection();
                }
            } else if (line.startsWith("body=[")) {
                currentLine++;
                classDef.setBody(parseBodyList());
                if (currentLine > 0) {
                    String lastLine = lines[currentLine - 1].trim();
                    if (lineClosesBodyAndParent(lastLine)) {
                        break;
                    }
                }
            } else if (line.startsWith("decorator_list=[")) {
                if (line.endsWith("[])") || line.endsWith("[]),")) {
                    currentLine++;
                    break;
                }
                skipBracketedSection();
            } else if (line.startsWith("type_params=[")) {
                if (line.endsWith("[])") || line.endsWith("[]),")) {
                    currentLine++;
                    break;
                }
                skipBracketedSection();
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }

        return classDef;
    }
}
