package in.ramanujan.translation.codeConverter.ast;

import in.ramanujan.translation.codeConverter.exception.CompilationException;
import java.util.*;
import java.util.regex.*;

/**
 * AstParser parses Python AST dump strings (generated by `python3 -m ast`) into Java AST node objects.
 * 
 * <p>This parser uses a line-by-line state machine approach to convert the textual AST representation
 * into a structured tree of Java objects that can be traversed and converted to RuleEngineInput.</p>
 * 
 * <h3>Python AST Dump Format</h3>
 * <p>Python's AST module outputs a nested structure like:</p>
 * <pre>
 * Module(
 *   body=[
 *     Assign(
 *       targets=[Name(id='x', ctx=Store())],
 *       value=Constant(value=5))],
 *   type_ignores=[])
 * </pre>
 * 
 * <h3>Supported Python Constructs</h3>
 * <ul>
 *   <li><b>Assignments:</b> x = 5, arr[0] = 10</li>
 *   <li><b>Augmented Assignments:</b> x += 1, y *= 2</li>
 *   <li><b>Binary Operations:</b> x + y, a * b - c</li>
 *   <li><b>Comparisons:</b> x &gt; 5, a == b, y &lt;= 10</li>
 *   <li><b>Control Flow:</b> if/else, while loops</li>
 *   <li><b>Functions:</b> def func(a, b): return a + b</li>
 *   <li><b>Arrays/Lists:</b> [1, 2, 3], arr[index]</li>
 *   <li><b>Function Calls:</b> func(x, y)</li>
 * </ul>
 * 
 * <h3>Usage Example</h3>
 * <pre>
 * PythonAstInvoker invoker = new PythonAstInvoker();
 * String pythonCode = "x = 5\ny = x + 10";
 * String astDump = invoker.invokeAst(pythonCode);
 * 
 * AstParser parser = new AstParser();
 * ModuleNode module = parser.parse(astDump);
 * 
 * // Traverse the AST
 * for (AstNode node : module.getBody()) {
 *     if (node instanceof AssignNode) {
 *         AssignNode assign = (AssignNode) node;
 *         // Process assignment...
 *     }
 * }
 * </pre>
 * 
 * @see ModuleNode
 * @see AssignNode
 * @see BinOpNode
 * @see IfNode
 * @see WhileNode
 */
public class AstParser {
    
    private String[] lines;
    private int currentLine;
    
    /**
     * Parses a Python AST dump string into a ModuleNode tree structure.
     * 
     * <p><b>Python Code Example:</b></p>
     * <pre>
     * x = 5
     * y = 10
     * z = x + y
     * </pre>
     * 
     * <p><b>AST Dump Input:</b></p>
     * <pre>
     * Module(
     *   body=[
     *     Assign(targets=[Name(id='x', ctx=Store())], value=Constant(value=5)),
     *     Assign(targets=[Name(id='y', ctx=Store())], value=Constant(value=10)),
     *     Assign(targets=[Name(id='z', ctx=Store())], 
     *            value=BinOp(left=Name(id='x', ctx=Load()), op=Add(), right=Name(id='y', ctx=Load())))],
     *   type_ignores=[])
     * </pre>
     * 
     * <p><b>Output:</b> A ModuleNode containing 3 AssignNode objects in its body list.</p>
     * 
     * @param astDump The complete AST dump string from Python's ast module
     * @return ModuleNode representing the root of the parsed AST tree
     * @throws CompilationException If the AST dump doesn't start with Module or has invalid format
     */
    public ModuleNode parse(String astDump) throws CompilationException {
        lines = astDump.split("\n");
        currentLine = 0;
        
        // First line should be "Module("
        String firstLine = lines[0].trim();
        if (!firstLine.startsWith("Module(")) {
            throw new CompilationException(null, null, 
                "Expected Module at root, got: " + firstLine);
        }
        
        ModuleNode module = new ModuleNode();
        currentLine = 1; // Skip "Module("
        
        // Parse body
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            if (line.startsWith("body=[")) {
                currentLine++;
                module.setBody(parseBodyList());
                break;
            }
            currentLine++;
        }
        
        return module;
    }
    
    /**
     * Parses a list of statements within a body block (Module, If, While, FunctionDef).
     * 
     * <p><b>Example - If statement body:</b></p>
     * <pre>
     * if x > 5:
     *     y = 10
     *     z = 20
     * </pre>
     * 
     * <p><b>AST Fragment:</b></p>
     * <pre>
     * body=[
     *   Assign(targets=[Name(id='y', ctx=Store())], value=Constant(value=10)),
     *   Assign(targets=[Name(id='z', ctx=Store())], value=Constant(value=20))]
     * </pre>
     * 
     * @return List of AstNode objects representing statements in the body
     * @throws CompilationException If statement parsing fails
     */
    private List<AstNode> parseBodyList() throws CompilationException {
        List<AstNode> body = new ArrayList<>();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("]")) {
                currentLine++;
                break;
            }
            
            AstNode node = parseNode(line);
            if (node != null) {
                body.add(node);
            }
        }
        
        return body;
    }
    
    /**
     * Routes a line to the appropriate node parser based on the node type.
     * 
     * <p>Recognized node types and their Python equivalents:</p>
     * <ul>
     *   <li><b>Assign:</b> x = 5</li>
     *   <li><b>AugAssign:</b> x += 1</li>
     *   <li><b>If:</b> if x > 5: ...</li>
     *   <li><b>While:</b> while x < 10: ...</li>
     *   <li><b>FunctionDef:</b> def func(): ...</li>
     *   <li><b>Expr:</b> print(x)  (expression statement)</li>
     *   <li><b>Return:</b> return x</li>
     * </ul>
     * 
     * @param line The current line containing the node type
     * @return Parsed AstNode or null if node type is unrecognized
     * @throws CompilationException If parsing the specific node type fails
     */
    private AstNode parseNode(String line) throws CompilationException {
        line = line.trim();
        
        if (line.startsWith("Assign(")) {
            return parseAssign();
        } else if (line.startsWith("AugAssign(")) {
            return parseAugAssign();
        } else if (line.startsWith("If(")) {
            return parseIf();
        } else if (line.startsWith("While(")) {
            return parseWhile();
        } else if (line.startsWith("FunctionDef(")) {
            return parseFunctionDef();
        } else if (line.startsWith("Expr(")) {
            return parseExpr();
        } else if (line.startsWith("Return(")) {
            return parseReturn();
        }
        
        currentLine++;
        return null;
    }
    
    /**
     * Parses an assignment statement.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * # Simple assignment
     * x = 5
     * 
     * # Multiple targets
     * a = b = 10
     * 
     * # Array assignment
     * arr[0] = 100
     * 
     * # Expression assignment
     * result = x + y * z
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * Assign(
     *   targets=[Name(id='x', ctx=Store())],
     *   value=Constant(value=5))
     * </pre>
     * 
     * <p><b>Result:</b> AssignNode with targets list and value node.</p>
     * 
     * @return AssignNode containing target(s) and value
     * @throws CompilationException If assignment structure is invalid
     */
    private AssignNode parseAssign() throws CompilationException {
        AssignNode assign = new AssignNode();
        currentLine++;
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("targets=[")) {
                currentLine++;
                assign.setTargets(parseTargetsList());
            } else if (line.startsWith("value=")) {
                assign.setValue(parseValue(line));
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return assign;
    }
    
    /**
     * Parses the list of assignment targets.
     * 
     * <p><b>Examples:</b></p>
     * <pre>
     * x = 5              # targets=[Name]
     * arr[0] = 10        # targets=[Subscript]
     * a = b = c = 0      # targets=[Name, Name, Name]
     * </pre>
     * 
     * @return List of target nodes (NameNode or SubscriptNode)
     * @throws CompilationException If target parsing fails
     */
    private List<AstNode> parseTargetsList() throws CompilationException {
        List<AstNode> targets = new ArrayList<>();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("]")) {
                currentLine++;
                break;
            }
            
            if (line.startsWith("Name(")) {
                targets.add(parseName());
            } else if (line.startsWith("Subscript(")) {
                targets.add(parseSubscript());
            } else {
                currentLine++;
            }
        }
        
        return targets;
    }
    
    /**
     * Parses a Name node representing a variable reference.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * x = 5           # Name(id='x', ctx=Store())  - assignment target
     * y = x + 1       # Name(id='x', ctx=Load())   - reading variable
     * arr = mylist    # Name(id='mylist', ctx=Load())
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * Name(id='variableName', ctx=Store())  # or ctx=Load()
     * </pre>
     * 
     * <p>Context types:</p>
     * <ul>
     *   <li><b>Store:</b> Variable is being assigned to</li>
     *   <li><b>Load:</b> Variable value is being read</li>
     * </ul>
     * 
     * @return NameNode with id and context
     * @throws CompilationException If name format is invalid
     */
    private NameNode parseName() throws CompilationException {
        NameNode name = new NameNode();
        String line = lines[currentLine].trim();
        
        // Extract id from "Name(id='varName', ctx=Store())"
        Pattern pattern = Pattern.compile("id='([^']+)'");
        Matcher matcher = pattern.matcher(line);
        if (matcher.find()) {
            name.setId(matcher.group(1));
        }
        
        if (line.contains("ctx=Store()")) {
            name.setCtx("Store");
        } else if (line.contains("ctx=Load()")) {
            name.setCtx("Load");
        }
        
        // Skip closing parenthesis if on same line
        if (!line.endsWith(")") && !line.endsWith("),")) {
            currentLine++;
            // Find closing paren
            while (currentLine < lines.length) {
                line = lines[currentLine].trim();
                if (line.equals(")") || line.startsWith("),")) {
                    break;
                }
                currentLine++;
            }
        }
        currentLine++;
        return name;
    }
    
    /**
     * Parses a value expression (right-hand side of assignments, conditions, etc.).
     * 
     * <p><b>Supported value types:</b></p>
     * <pre>
     * 5                    # Constant
     * x                    # Name
     * x + y                # BinOp
     * func(a, b)           # Call
     * [1, 2, 3]            # List
     * arr[0]               # Subscript
     * x > 5                # Compare
     * </pre>
     * 
     * @param line The line containing the value expression
     * @return Parsed value node (ConstantNode, NameNode, BinOpNode, etc.)
     * @throws CompilationException If value type is unrecognized
     */
    private AstNode parseValue(String line) throws CompilationException {
        if (line.contains("Constant(")) {
            return parseConstant(line);
        } else if (line.contains("BinOp(")) {
            currentLine++;
            return parseBinOp();
        } else if (line.contains("Name(")) {
            currentLine++;
            return parseName();
        } else if (line.contains("Call(")) {
            currentLine++;
            return parseCall();
        } else if (line.contains("List(")) {
            currentLine++;
            return parseList();
        } else if (line.contains("Subscript(")) {
            currentLine++;
            return parseSubscript();
        } else if (line.contains("Compare(")) {
            currentLine++;
            return parseCompare();
        }
        
        currentLine++;
        return null;
    }
    
    /**
     * Parses a constant literal value.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * 42              # Constant(value=42)        - Integer
     * 3.14            # Constant(value=3.14)      - Double
     * "hello"         # Constant(value='hello')   - String
     * True            # Constant(value=True)      - Boolean
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * Constant(value=42)
     * Constant(value=3.14)
     * Constant(value='hello')
     * </pre>
     * 
     * @param line The line containing the constant value
     * @return ConstantNode with parsed value (Integer, Double, or String)
     */
    private ConstantNode parseConstant(String line) {
        ConstantNode constant = new ConstantNode();
        
        // Extract value from "Constant(value=123)" or "value=Constant(value=123)"
        Pattern pattern = Pattern.compile("value=([^),]+)");
        Matcher matcher = pattern.matcher(line);
        if (matcher.find()) {
            String valueStr = matcher.group(1).trim();
            try {
                if (valueStr.contains(".")) {
                    constant.setValue(Double.parseDouble(valueStr));
                } else {
                    constant.setValue(Integer.parseInt(valueStr));
                }
            } catch (NumberFormatException e) {
                // String value - remove quotes
                constant.setValue(valueStr.replaceAll("'", "").replaceAll("\"", ""));
            }
        }
        
        currentLine++;
        return constant;
    }
    
    /**
     * Parses a binary operation.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * x + y              # BinOp(left=Name('x'), op=Add(), right=Name('y'))
     * a - b              # BinOp(left=Name('a'), op=Sub(), right=Name('b'))
     * 2 * 3              # BinOp(left=Constant(2), op=Mult(), right=Constant(3))
     * x / y              # BinOp(left=Name('x'), op=Div(), right=Name('y'))
     * a ** b             # BinOp(left=Name('a'), op=Pow(), right=Name('b'))
     * x % y              # BinOp(left=Name('x'), op=Mod(), right=Name('y'))
     * </pre>
     * 
     * <p><b>Complex expression:</b></p>
     * <pre>
     * result = x + y * z
     * # BinOp(
     * #   left=Name('x'),
     * #   op=Add(),
     * #   right=BinOp(left=Name('y'), op=Mult(), right=Name('z')))
     * </pre>
     * 
     * <p><b>Supported operators:</b> Add, Sub, Mult, Div, Mod, Pow, FloorDiv, LShift, RShift, BitOr, BitXor, BitAnd</p>
     * 
     * @return BinOpNode with left operand, operator, and right operand
     * @throws CompilationException If binary operation structure is invalid
     */
    private BinOpNode parseBinOp() throws CompilationException {
        BinOpNode binOp = new BinOpNode();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("left=")) {
                binOp.setLeft(parseValue(line));
            } else if (line.startsWith("op=")) {
                binOp.setOp(extractOp(line));
                currentLine++;
            } else if (line.startsWith("right=")) {
                binOp.setRight(parseValue(line));
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return binOp;
    }
    
    /**
     * Extracts operator name from AST line.
     * 
     * <p><b>Examples:</b></p>
     * <pre>
     * "op=Add()"    -> "Add"
     * "op=Sub()"    -> "Sub"
     * "op=Mult()"   -> "Mult"
     * </pre>
     * 
     * @param line The line containing the operator
     * @return Operator name as string (e.g., "Add", "Sub", "Mult")
     */
    private String extractOp(String line) {
        // Extract "Add()" -> "Add", "Sub()" -> "Sub", etc.
        Pattern pattern = Pattern.compile("op=([A-Za-z]+)\\(\\)");
        Matcher matcher = pattern.matcher(line);
        if (matcher.find()) {
            return matcher.group(1);
        }
        return "";
    }
    
    /**
     * Parses a comparison operation.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * x > 5              # Compare(left=Name('x'), ops=[Gt()], comparators=[Constant(5)])
     * a == b             # Compare(left=Name('a'), ops=[Eq()], comparators=[Name('b')])
     * y <= 10            # Compare(left=Name('y'), ops=[LtE()], comparators=[Constant(10)])
     * x != 0             # Compare(left=Name('x'), ops=[NotEq()], comparators=[Constant(0)])
     * 
     * # Chained comparison
     * 0 < x < 10         # Compare(left=Constant(0), ops=[Lt(), Lt()], 
     *                    #         comparators=[Name('x'), Constant(10)])
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * Compare(
     *   left=Name(id='x', ctx=Load()),
     *   ops=[Gt()],
     *   comparators=[Constant(value=5)])
     * </pre>
     * 
     * <p><b>Comparison operators:</b> Lt (&lt;), LtE (&lt;=), Gt (&gt;), GtE (&gt;=), Eq (==), NotEq (!=), Is, IsNot, In, NotIn</p>
     * 
     * @return CompareNode with left side, operators list, and comparators list
     * @throws CompilationException If comparison structure is invalid
     */
    private CompareNode parseCompare() throws CompilationException {
        CompareNode compare = new CompareNode();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("left=")) {
                compare.setLeft(parseValue(line));
            } else if (line.startsWith("ops=[")) {
                currentLine++;
                compare.setOps(parseOpsList());
            } else if (line.startsWith("comparators=[")) {
                currentLine++;
                compare.setComparators(parseComparatorsList());
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return compare;
    }
    
    /**
     * Parses the list of comparison operators.
     * 
     * <p><b>Examples:</b></p>
     * <pre>
     * x > 5              # ops=[Gt()]
     * 0 < x < 10         # ops=[Lt(), Lt()]
     * </pre>
     * 
     * @return List of operator names (e.g., ["Lt", "Gt", "Eq"])
     */
    private List<String> parseOpsList() {
        List<String> ops = new ArrayList<>();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("]")) {
                currentLine++;
                break;
            }
            
            // Extract "Lt()" -> "Lt"
            Pattern pattern = Pattern.compile("([A-Za-z]+)\\(\\)");
            Matcher matcher = pattern.matcher(line);
            if (matcher.find()) {
                ops.add(matcher.group(1));
            }
            
            currentLine++;
        }
        
        return ops;
    }
    
    /**
     * Parses the list of values being compared against.
     * 
     * <p><b>Examples:</b></p>
     * <pre>
     * x > 5              # comparators=[Constant(5)]
     * a == b             # comparators=[Name('b')]
     * 0 < x < 10         # comparators=[Name('x'), Constant(10)]
     * </pre>
     * 
     * @return List of comparator nodes
     * @throws CompilationException If comparator parsing fails
     */
    private List<AstNode> parseComparatorsList() throws CompilationException {
        List<AstNode> comparators = new ArrayList<>();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("]")) {
                currentLine++;
                break;
            }
            
            if (line.startsWith("Name(")) {
                comparators.add(parseName());
            } else if (line.startsWith("Constant(")) {
                comparators.add(parseConstant(line));
            } else {
                currentLine++;
            }
        }
        
        return comparators;
    }
    
    /**
     * Parses an if statement with optional else block.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * # Simple if
     * if x > 5:
     *     y = 10
     * 
     * # If-else
     * if x > 5:
     *     y = 10
     * else:
     *     y = 20
     * 
     * # If-elif-else
     * if x > 10:
     *     y = 1
     * elif x > 5:
     *     y = 2
     * else:
     *     y = 3
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * If(
     *   test=Compare(left=Name('x'), ops=[Gt()], comparators=[Constant(5)]),
     *   body=[
     *     Assign(targets=[Name('y')], value=Constant(10))],
     *   orelse=[
     *     Assign(targets=[Name('y')], value=Constant(20))])
     * </pre>
     * 
     * @return IfNode with test condition, body statements, and optional else statements
     * @throws CompilationException If if statement structure is invalid
     */
    private IfNode parseIf() throws CompilationException {
        IfNode ifNode = new IfNode();
        currentLine++;
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("test=")) {
                ifNode.setTest(parseValue(line));
            } else if (line.startsWith("body=[")) {
                currentLine++;
                ifNode.setBody(parseBodyList());
            } else if (line.startsWith("orelse=[")) {
                currentLine++;
                ifNode.setOrelse(parseBodyList());
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return ifNode;
    }
    
    /**
     * Parses a while loop.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * # Simple while loop
     * while x < 10:
     *     x = x + 1
     * 
     * # While with complex condition
     * while x > 0 and y < 100:
     *     x = x - 1
     *     y = y + 2
     * 
     * # While-else (else executes if loop completes normally)
     * while x < 10:
     *     x = x + 1
     * else:
     *     print("Done")
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * While(
     *   test=Compare(left=Name('x'), ops=[Lt()], comparators=[Constant(10)]),
     *   body=[
     *     AugAssign(target=Name('x'), op=Add(), value=Constant(1))],
     *   orelse=[])
     * </pre>
     * 
     * @return WhileNode with test condition, body statements, and optional else statements
     * @throws CompilationException If while loop structure is invalid
     */
    private WhileNode parseWhile() throws CompilationException {
        WhileNode whileNode = new WhileNode();
        currentLine++;
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("test=")) {
                whileNode.setTest(parseValue(line));
            } else if (line.startsWith("body=[")) {
                currentLine++;
                whileNode.setBody(parseBodyList());
            } else if (line.startsWith("orelse=[")) {
                currentLine++;
                whileNode.setOrelse(parseBodyList());
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return whileNode;
    }
    
    /**
     * Parses a function definition.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * # Simple function
     * def add(a, b):
     *     return a + b
     * 
     * # Function with multiple statements
     * def calculate(x, y, z):
     *     temp = x + y
     *     result = temp * z
     *     return result
     * 
     * # Function with no parameters
     * def greet():
     *     print("Hello")
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * FunctionDef(
     *   name='add',
     *   args=arguments(
     *     posonlyargs=[],
     *     args=[arg(arg='a'), arg(arg='b')],
     *     kwonlyargs=[],
     *     kw_defaults=[],
     *     defaults=[]),
     *   body=[
     *     Return(value=BinOp(left=Name('a'), op=Add(), right=Name('b')))],
     *   decorator_list=[])
     * </pre>
     * 
     * @return FunctionDefNode with name, arguments, and body statements
     * @throws CompilationException If function definition structure is invalid
     */
    private FunctionDefNode parseFunctionDef() throws CompilationException {
        FunctionDefNode funcDef = new FunctionDefNode();
        String line = lines[currentLine].trim();
        
        // Extract name
        Pattern namePattern = Pattern.compile("name='([^']+)'");
        Matcher nameMatcher = namePattern.matcher(line);
        if (nameMatcher.find()) {
            funcDef.setName(nameMatcher.group(1));
        }
        
        currentLine++;
        
        while (currentLine < lines.length) {
            line = lines[currentLine].trim();
            
            if (line.startsWith("args=arguments(")) {
                funcDef.setArgs(parseArguments());
            } else if (line.startsWith("body=[")) {
                currentLine++;
                funcDef.setBody(parseBodyList());
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return funcDef;
    }
    
    /**
     * Parses function arguments specification.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * def func():              # arguments(args=[])
     * def func(a):             # arguments(args=[arg('a')])
     * def func(a, b, c):       # arguments(args=[arg('a'), arg('b'), arg('c')])
     * </pre>
     * 
     * @return ArgumentsNode containing list of argument names
     */
    private ArgumentsNode parseArguments() {
        ArgumentsNode arguments = new ArgumentsNode();
        currentLine++;
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("args=[")) {
                currentLine++;
                arguments.setArgs(parseArgsList());
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return arguments;
    }
    
    /**
     * Parses the list of individual function arguments.
     * 
     * <p><b>Examples:</b></p>
     * <pre>
     * args=[arg(arg='a'), arg(arg='b')]
     * # Results in: [ArgNode(arg='a'), ArgNode(arg='b')]
     * </pre>
     * 
     * @return List of ArgNode objects
     */
    private List<ArgNode> parseArgsList() {
        List<ArgNode> args = new ArrayList<>();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("]")) {
                currentLine++;
                break;
            }
            
            if (line.startsWith("arg(arg='") || line.contains("arg(arg='")) {
                ArgNode arg = new ArgNode();
                Pattern pattern = Pattern.compile("arg='([^']+)'");
                Matcher matcher = pattern.matcher(line);
                if (matcher.find()) {
                    arg.setArg(matcher.group(1));
                }
                args.add(arg);
            }
            
            currentLine++;
        }
        
        return args;
    }
    
    /**
     * Parses a function call expression.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * result = add(x, y)           # Call(func=Name('add'), args=[Name('x'), Name('y')])
     * print("hello")               # Call(func=Name('print'), args=[Constant('hello')])
     * calculate(1, 2, 3)           # Call(func=Name('calculate'), args=[Constant(1), Constant(2), Constant(3)])
     * arr.append(5)                # Call(func=Attribute(value=Name('arr'), attr='append'), args=[Constant(5)])
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * Call(
     *   func=Name(id='add', ctx=Load()),
     *   args=[Name(id='x', ctx=Load()), Name(id='y', ctx=Load())],
     *   keywords=[])
     * </pre>
     * 
     * @return CallNode with function reference and argument list
     * @throws CompilationException If function call structure is invalid
     */
    private CallNode parseCall() throws CompilationException {
        CallNode call = new CallNode();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("func=")) {
                call.setFunc(parseValue(line));
            } else if (line.startsWith("args=[")) {
                currentLine++;
                call.setArgs(parseCallArgsList());
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return call;
    }
    
    /**
     * Parses the argument list for a function call.
     * 
     * <p><b>Examples:</b></p>
     * <pre>
     * func()              # args=[]
     * func(x)             # args=[Name('x')]
     * func(x, 5, y+z)     # args=[Name('x'), Constant(5), BinOp(...)]
     * </pre>
     * 
     * @return List of argument nodes
     * @throws CompilationException If argument parsing fails
     */
    private List<AstNode> parseCallArgsList() throws CompilationException {
        List<AstNode> args = new ArrayList<>();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("]")) {
                currentLine++;
                break;
            }
            
            if (line.startsWith("Name(") || line.startsWith("Constant(") || 
                line.startsWith("BinOp(") || line.startsWith("Subscript(")) {
                AstNode arg = parseNode(line);
                if (arg != null) {
                    args.add(arg);
                }
            } else {
                currentLine++;
            }
        }
        
        return args;
    }
    
    /**
     * Parses array/list subscript access.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * x = arr[0]              # Subscript(value=Name('arr'), slice=Constant(0), ctx=Load())
     * arr[i] = 10             # Subscript(value=Name('arr'), slice=Name('i'), ctx=Store())
     * matrix[i][j]            # Nested subscripts
     * arr[i+1]                # Subscript with expression: slice=BinOp(...)
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * Subscript(
     *   value=Name(id='arr', ctx=Load()),
     *   slice=Constant(value=0),
     *   ctx=Load())
     * </pre>
     * 
     * @return SubscriptNode with array reference, index, and context
     * @throws CompilationException If subscript structure is invalid
     */
    private SubscriptNode parseSubscript() throws CompilationException {
        SubscriptNode subscript = new SubscriptNode();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("value=")) {
                subscript.setValue(parseValue(line));
            } else if (line.startsWith("slice=")) {
                subscript.setSlice(parseValue(line));
            } else if (line.contains("ctx=Store()")) {
                subscript.setCtx("Store");
                currentLine++;
            } else if (line.contains("ctx=Load()")) {
                subscript.setCtx("Load");
                currentLine++;
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return subscript;
    }
    
    /**
     * Parses a list literal.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * arr = []                    # List(elts=[], ctx=Load())
     * arr = [1, 2, 3]             # List(elts=[Constant(1), Constant(2), Constant(3)], ctx=Load())
     * arr = [x, y, z]             # List(elts=[Name('x'), Name('y'), Name('z')], ctx=Load())
     * arr = [x+1, y*2]            # List(elts=[BinOp(...), BinOp(...)], ctx=Load())
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * List(
     *   elts=[Constant(value=1), Constant(value=2), Constant(value=3)],
     *   ctx=Load())
     * </pre>
     * 
     * @return ListNode with elements list
     * @throws CompilationException If list structure is invalid
     */
    private ListNode parseList() throws CompilationException {
        ListNode list = new ListNode();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("elts=[")) {
                currentLine++;
                list.setElts(parseEltsList());
            } else if (line.contains("ctx=Load()")) {
                list.setCtx("Load");
                currentLine++;
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return list;
    }
    
    /**
     * Parses the elements of a list literal.
     * 
     * <p><b>Examples:</b></p>
     * <pre>
     * [1, 2, 3]              # elts=[Constant(1), Constant(2), Constant(3)]
     * [x, y]                 # elts=[Name('x'), Name('y')]
     * </pre>
     * 
     * @return List of element nodes
     * @throws CompilationException If element parsing fails
     */
    private List<AstNode> parseEltsList() throws CompilationException {
        List<AstNode> elts = new ArrayList<>();
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("]")) {
                currentLine++;
                break;
            }
            
            AstNode elt = parseNode(line);
            if (elt != null) {
                elts.add(elt);
            }
        }
        
        return elts;
    }
    
    /**
     * Parses an expression statement.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * print(x)               # Expr(value=Call(func=Name('print'), args=[Name('x')]))
     * arr.append(5)          # Expr(value=Call(...))
     * x + y                  # Expr(value=BinOp(...))  (rarely used alone)
     * </pre>
     * 
     * <p>Expression statements are standalone expressions that are evaluated but their
     * result is not assigned to anything. Commonly used for function calls with side effects.</p>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * Expr(
     *   value=Call(func=Name('print'), args=[Name('x')]))
     * </pre>
     * 
     * @return ExprNode wrapping the expression value
     * @throws CompilationException If expression structure is invalid
     */
    private ExprNode parseExpr() throws CompilationException {
        ExprNode expr = new ExprNode();
        currentLine++;
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("value=")) {
                expr.setValue(parseValue(line));
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return expr;
    }
    
    /**
     * Parses a return statement.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * return x               # Return(value=Name('x'))
     * return 42              # Return(value=Constant(42))
     * return x + y           # Return(value=BinOp(left=Name('x'), op=Add(), right=Name('y')))
     * return                 # Return(value=None)
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * Return(
     *   value=BinOp(
     *     left=Name(id='a', ctx=Load()),
     *     op=Add(),
     *     right=Name(id='b', ctx=Load())))
     * </pre>
     * 
     * @return ReturnNode with optional return value
     * @throws CompilationException If return statement structure is invalid
     */
    private ReturnNode parseReturn() throws CompilationException {
        ReturnNode returnNode = new ReturnNode();
        currentLine++;
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("value=")) {
                returnNode.setValue(parseValue(line));
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return returnNode;
    }
    
    /**
     * Parses an augmented assignment statement.
     * 
     * <p><b>Python Examples:</b></p>
     * <pre>
     * x += 5                 # AugAssign(target=Name('x'), op=Add(), value=Constant(5))
     * y -= 3                 # AugAssign(target=Name('y'), op=Sub(), value=Constant(3))
     * z *= 2                 # AugAssign(target=Name('z'), op=Mult(), value=Constant(2))
     * count /= 10            # AugAssign(target=Name('count'), op=Div(), value=Constant(10))
     * arr[i] += 1            # AugAssign(target=Subscript(...), op=Add(), value=Constant(1))
     * </pre>
     * 
     * <p><b>AST Format:</b></p>
     * <pre>
     * AugAssign(
     *   target=Name(id='x', ctx=Store()),
     *   op=Add(),
     *   value=Constant(value=5))
     * </pre>
     * 
     * <p>Augmented assignments combine an operation with assignment:</p>
     * <ul>
     *   <li>x += y  is equivalent to  x = x + y</li>
     *   <li>x *= y  is equivalent to  x = x * y</li>
     *   <li>x -= y  is equivalent to  x = x - y</li>
     * </ul>
     * 
     * @return AugAssignNode with target, operator, and value
     * @throws CompilationException If augmented assignment structure is invalid
     */
    private AugAssignNode parseAugAssign() throws CompilationException {
        AugAssignNode augAssign = new AugAssignNode();
        currentLine++;
        
        while (currentLine < lines.length) {
            String line = lines[currentLine].trim();
            
            if (line.startsWith("target=")) {
                augAssign.setTarget(parseValue(line));
            } else if (line.startsWith("op=")) {
                augAssign.setOp(extractOp(line));
                currentLine++;
            } else if (line.startsWith("value=")) {
                augAssign.setValue(parseValue(line));
            } else if (line.equals(")") || line.startsWith("),")) {
                currentLine++;
                break;
            } else {
                currentLine++;
            }
        }
        
        return augAssign;
    }
}
