# === AUTO-GENERATED Phi-3 Inference Kernel (unrolled) ===
# Layers: 2  VOCAB: 32064  HIDDEN: 3072
# INTERMEDIATE: 8192  HEADS: 32  HD: 96  MAX_SEQ: 64
# Generated by extract_weights.py — do not edit manually.
# If forward_layer() works, use inference_kernel.py instead.

# =============================================================================
# Phi-3-mini-4k-instruct GPU Inference Kernel
# =============================================================================
#
# Architecture: VOCAB=32064  HIDDEN=3072  INTER=8192  HEADS=32  HD=96
#               LAYERS=32  MAX_SEQ=64  RoPE theta=10000  HD_HALF=48
#
# IMPORTANT: Large matrix multiplications (QKV projection, gate_up, down_proj)
# are done HOST-SIDE because their flat weight indices exceed float32's exact
# integer range (2^24 = 16,777,216).  Only element-wise and small-index ops
# run on the GPU.
#
# CSV injection: single-row CSVs -> 1D in GPU kernels, 2D via [0][idx] on host.
#
# After execution, query:
#   var best_id       -> predicted token ID
#   var best_val      -> max logit value
# =============================================================================

# ── Activation buffers (1D flat, all < 16M indices -> GPU safe) ──────────────
hidden   = [0 for _ in range(196608)]
normed   = [0 for _ in range(196608)]
q_buf    = [0 for _ in range(196608)]
k_buf    = [0 for _ in range(196608)]
v_buf    = [0 for _ in range(196608)]
attn_sc  = [0 for _ in range(4096)]
concat   = [0 for _ in range(196608)]
gate_buf = [0 for _ in range(524288)]
up_buf   = [0 for _ in range(524288)]
rms_vals = [0 for _ in range(64)]
head_buf = [0 for _ in range(1)]
tok_ids  = [0 for _ in range(64)]
last_h   = [0 for _ in range(3072)]
logits   = [0 for _ in range(32064)]

# Scalar results
best_id  = 0
best_val = 0


# =============================================================================
# GPU KERNELS  (all array indices guaranteed < 16,777,216)
# =============================================================================

# RMS norm apply: out[gid] = vec[gid] * inv_rms[pos] * weight[dim]
def rms_apply_GPU_1(vec, rms_vals, weight, out, gid):
    pos = gid / 3072
    dim = gid - pos * 3072
    rv  = rms_vals[pos]
    out[gid] = vec[gid] * rv * weight[dim]

# RoPE: split-half rotation (Llama/Phi-3 style)
# x1 = x[0:48], x2 = x[48:96]
# result[0:48]  = x1*cos - x2*sin
# result[48:96] = x2*cos + x1*sin
def rope_GPU_1(q_buf, k_buf, rope_cos, rope_sin, gid):
    pos  = gid / 1536
    pi   = gid - pos * 1536
    head = pi / 48
    pair = pi - head * 48
    base = pos * 3072 + head * 96
    i0   = base + pair
    i1   = base + 48 + pair
    ri   = pos * 48 + pair
    c    = rope_cos[ri]
    s    = rope_sin[ri]
    q0   = q_buf[i0]
    q1   = q_buf[i1]
    q_buf[i0] = q0 * c - q1 * s
    q_buf[i1] = q1 * c + q0 * s
    k0   = k_buf[i0]
    k1   = k_buf[i1]
    k_buf[i0] = k0 * c - k1 * s
    k_buf[i1] = k1 * c + k0 * s

# Attention scores: dot(Q_head, K_head) / sqrt(96) for (t1, t2)
def attn_score_GPU_1(q_buf, k_buf, attn_sc, head_buf, gid):
    t1   = gid / 64
    t2   = gid - t1 * 64
    hoff = head_buf[0] * 96
    acc  = 0
    d    = 0
    while d < 96:
        qi  = t1 * 3072 + hoff + d
        ki  = t2 * 3072 + hoff + d
        acc = acc + q_buf[qi] * k_buf[ki]
        d   = d + 1
    attn_sc[gid] = acc * 0.10206207

# Attention context: weighted V sum for (t1, d) within head
def attn_ctx_GPU_1(attn_sc, v_buf, concat, head_buf, gid):
    t1   = gid / 96
    d    = gid - t1 * 96
    hoff = head_buf[0] * 96
    acc  = 0
    t2   = 0
    while t2 < 64:
        si  = t1 * 64 + t2
        vi  = t2 * 3072 + hoff + d
        acc = acc + attn_sc[si] * v_buf[vi]
        t2  = t2 + 1
    ci         = t1 * 3072 + hoff + d
    concat[ci] = acc

# Output projection + residual (host-side, o_w is multi-row [3072, 3072])
def host_out_proj_res(o_w):
    pos = 0
    while pos < 64:
        d_out = 0
        while d_out < 3072:
            acc = 0
            di  = 0
            while di < 3072:
                ci  = pos * 3072 + di
                acc = acc + concat[ci] * o_w[d_out][di]
                di  = di + 1
            hi = pos * 3072 + d_out
            hidden[hi] = hidden[hi] + acc
            d_out = d_out + 1
        pos = pos + 1

# SiLU activation: gate = silu(gate) * up
# silu(x) = x / (1 + exp(-x))
def silu_mul_GPU_1(gate_buf, up_buf, gid):
    x  = gate_buf[gid]
    nx = 0 - x
    EXP(nx)
    sig = 1 / (1 + nx)
    gate_buf[gid] = x * sig * up_buf[gid]


# =============================================================================
# HOST-SIDE HELPERS  (double precision, no index overflow)
# =============================================================================

def rms_norm_compute(vec):
    pos = 0
    while pos < 64:
        acc = 0
        d   = 0
        while d < 3072:
            idx = pos * 3072 + d
            acc = acc + vec[idx] * vec[idx]
            d   = d + 1
        acc = acc / 3072 + 0.00001
        SQRT(acc)
        rms_vals[pos] = 1 / acc
        pos = pos + 1

def softmax_attn():
    t1 = 0
    while t1 < 64:
        t2 = t1 + 1
        while t2 < 64:
            idx = t1 * 64 + t2
            attn_sc[idx] = -1000000
            t2 = t2 + 1
        mx = attn_sc[t1 * 64]
        j  = 1
        while j <= t1:
            idx = t1 * 64 + j
            if attn_sc[idx] > mx:
                mx = attn_sc[idx]
            j = j + 1
        sm = 0
        j  = 0
        while j <= t1:
            idx = t1 * 64 + j
            v   = attn_sc[idx] - mx
            EXP(v)
            attn_sc[idx] = v
            sm = sm + v
            j  = j + 1
        j = 0
        while j <= t1:
            idx = t1 * 64 + j
            attn_sc[idx] = attn_sc[idx] / sm
            j = j + 1
        t2 = t1 + 1
        while t2 < 64:
            idx = t1 * 64 + t2
            attn_sc[idx] = 0
            t2 = t2 + 1
        t1 = t1 + 1

# --------------------------------------------------------------------------
# HOST-SIDE MATRIX MULTIPLICATIONS
# Weight CSVs are single-row -> accessed as weight[0][flat_idx] on host.
# Host uses Java double -> indices up to 2^53 are exact.  No overflow.
# --------------------------------------------------------------------------

def host_qkv_proj(qkv_w):
    # qkv_w is multi-row CSV: [9216, 3072]
    # Q rows 0:3072, K rows 3072:6144, V rows 6144:9216
    pos = 0
    while pos < 64:
        d_out = 0
        while d_out < 3072:
            aq = 0
            ak = 0
            av = 0
            di = 0
            q_row = d_out
            k_row = 3072 + d_out
            v_row = 6144 + d_out
            while di < 3072:
                xi = pos * 3072 + di
                xv = normed[xi]
                aq = aq + xv * qkv_w[q_row][di]
                ak = ak + xv * qkv_w[k_row][di]
                av = av + xv * qkv_w[v_row][di]
                di = di + 1
            oi = pos * 3072 + d_out
            q_buf[oi] = aq
            k_buf[oi] = ak
            v_buf[oi] = av
            d_out = d_out + 1
        pos = pos + 1

def host_gate_up_proj(gu_w):
    # gu_w is multi-row CSV: [16384, 3072]
    # gate rows 0:8192, up rows 8192:16384
    pos = 0
    while pos < 64:
        d_out = 0
        while d_out < 8192:
            ag = 0
            au = 0
            di = 0
            g_row = d_out
            u_row = 8192 + d_out
            while di < 3072:
                xi = pos * 3072 + di
                xv = normed[xi]
                ag = ag + xv * gu_w[g_row][di]
                au = au + xv * gu_w[u_row][di]
                di = di + 1
            gi = pos * 8192 + d_out
            gate_buf[gi] = ag
            up_buf[gi]   = au
            d_out = d_out + 1
        pos = pos + 1

def host_down_proj_res(down_w):
    # down_w is multi-row CSV: [3072, 8192]
    pos = 0
    while pos < 64:
        d_out = 0
        while d_out < 3072:
            acc = 0
            di  = 0
            while di < 8192:
                gi  = pos * 8192 + di
                acc = acc + gate_buf[gi] * down_w[d_out][di]
                di  = di + 1
            hi = pos * 3072 + d_out
            hidden[hi] = hidden[hi] + acc
            d_out = d_out + 1
        pos = pos + 1


# =============================================================================
# FORWARD LAYER
# =============================================================================

def forward_layer(qkv_w, o_w, gu_w, d_w, iln_w, pln_w):
    rms_norm_compute(hidden)
    rms_apply_GPU_1(hidden, rms_vals, iln_w, normed, 196608)

    host_qkv_proj(qkv_w)

    rope_GPU_1(q_buf, k_buf, rope_cos, rope_sin, 98304)

    h = 0
    while h < 32:
        head_buf[0] = h
        attn_score_GPU_1(q_buf, k_buf, attn_sc, head_buf, 4096)
        softmax_attn()
        attn_ctx_GPU_1(attn_sc, v_buf, concat, head_buf, 6144)
        h = h + 1

    host_out_proj_res(o_w)

    rms_norm_compute(hidden)
    rms_apply_GPU_1(hidden, rms_vals, pln_w, normed, 196608)

    host_gate_up_proj(gu_w)

    silu_mul_GPU_1(gate_buf, up_buf, 524288)

    host_down_proj_res(d_w)


# =============================================================================
# MAIN EXECUTION
# =============================================================================

si = 0
while si < 64:
    tok_ids[si] = seq_input[0][si]
    si = si + 1
actual_seq = seq_input[0][64]

# Embedding lookup (host-side, multi-row CSV: embed_tokens[tid][dim])
pos = 0
while pos < 64:
    tid = tok_ids[pos]
    dim = 0
    while dim < 3072:
        hidden[pos * 3072 + dim] = embed_tokens[tid][dim]
        dim = dim + 1
    pos = pos + 1


# === LAYER CALLS ===

# --- Layer 0 ---
rms_norm_compute(hidden)
rms_apply_GPU_1(hidden, rms_vals, l0_iln, normed, 196608)
qkv_proj_GPU_1(normed, l0_qkv, q_buf, k_buf, v_buf, 196608)
rope_GPU_1(q_buf, k_buf, rope_cos, rope_sin, 98304)
lh = 0
while lh < 32:
    head_buf[0] = lh
    attn_score_GPU_1(q_buf, k_buf, attn_sc, head_buf, 4096)
    softmax_attn()
    attn_ctx_GPU_1(attn_sc, v_buf, concat, head_buf, 6144)
    lh = lh + 1
out_proj_res_GPU_1(concat, l0_o, hidden, 196608)
rms_norm_compute(hidden)
rms_apply_GPU_1(hidden, rms_vals, l0_pln, normed, 196608)
gate_up_GPU_1(normed, l0_gu, gate_buf, up_buf, 524288)
silu_mul_GPU_1(gate_buf, up_buf, 524288)
down_proj_res_GPU_1(gate_buf, l0_down, hidden, 196608)

# --- Layer 1 ---
rms_norm_compute(hidden)
rms_apply_GPU_1(hidden, rms_vals, l1_iln, normed, 196608)
qkv_proj_GPU_1(normed, l1_qkv, q_buf, k_buf, v_buf, 196608)
rope_GPU_1(q_buf, k_buf, rope_cos, rope_sin, 98304)
lh = 0
while lh < 32:
    head_buf[0] = lh
    attn_score_GPU_1(q_buf, k_buf, attn_sc, head_buf, 4096)
    softmax_attn()
    attn_ctx_GPU_1(attn_sc, v_buf, concat, head_buf, 6144)
    lh = lh + 1
out_proj_res_GPU_1(concat, l1_o, hidden, 196608)
rms_norm_compute(hidden)
rms_apply_GPU_1(hidden, rms_vals, l1_pln, normed, 196608)
gate_up_GPU_1(normed, l1_gu, gate_buf, up_buf, 524288)
silu_mul_GPU_1(gate_buf, up_buf, 524288)
down_proj_res_GPU_1(gate_buf, l1_down, hidden, 196608)

# === FINAL OUTPUT ===

rms_norm_compute(hidden)
lp = actual_seq - 1
di = 0
while di < 3072:
    idx = lp * 3072 + di
    rv  = rms_vals[lp]
    last_h[di] = hidden[idx] * rv * final_norm[di]
    di = di + 1

# LM Head (host-side, multi-row CSV: lm_head[vi][di])
vi = 0
while vi < 32064:
    acc = 0
    di  = 0
    while di < 3072:
        acc = acc + last_h[di] * lm_head[vi][di]
        di  = di + 1
    logits[vi] = acc
    vi = vi + 1

# Argmax
best_id  = 0
best_val = logits[0]
vi = 1
while vi < 32064:
    if logits[vi] > best_val:
        best_val = logits[vi]
        best_id  = vi
    vi = vi + 1
