
# FROM anapsix/alpine-java

# Pull base image.
FROM ubuntu:16.04
# Specify the platform as AMD64
# FROM --platform=linux/amd64 ubuntu:16.04

# Install OpenJDK-8
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Fix certificate issues
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME

WORKDIR /
COPY rest/target/rest-1.0-SNAPSHOT-fat.jar rest-1.0-SNAPSHOT-fat.jar
COPY config/application-config.json config.json

ENV RAMANUJAN_WS /

MAINTAINER PSAXENA
EXPOSE 8887:8887/tcp
CMD ["java","-jar", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5008", "rest-1.0-SNAPSHOT-fat.jar", "-conf", "config.json"]
