
# FROM anapsix/alpine-java

# Pull base image.
FROM ubuntu:16.04

# Install OpenJDK-8
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Fix certificate issues
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME

WORKDIR /
COPY rest/target/rest-1.0-SNAPSHOT-fat.jar rest-1.0-SNAPSHOT-fat.jar
COPY config/application-config.json config.json
COPY libnative.dylib libnative.dylib
# Set env variable of NATIVE_LIB_PATH with he path of the native library
ENV NATIVE_LIB_PATH /libnative.dylib
MAINTAINER PSAXENA
EXPOSE 8887:8887/tcp
CMD ["java","-jar","rest-1.0-SNAPSHOT-fat.jar", "-conf", "config.json"]
