/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "json/json.h"
#include "RuleEngineInput.hpp"
#include "Processor.hpp"
#include "DebugPoint.h"
/* Header for class in_robinhood_ramanujan_rule_engine_NativeProcessor */

#ifndef _Included_in_robinhood_ramanujan_rule_engine_NativeProcessor
#define _Included_in_robinhood_ramanujan_rule_engine_NativeProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     in_robinhood_ramanujan_rule_engine_NativeProcessor
 * Method:    process
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_in_ramanujan_rule_engine_NativeProcessor_process
        (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif