/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "input/RuleEngineInput.hpp"
#include "processing/Processor.hpp"
#include "processing/DebugPoint.h"
/* Header for class in_ramanujan_rule_engine_NativeProcessor */

#ifndef _Included_in_ramanujan_rule_engine_NativeProcessor
#define _Included_in_ramanujan_rule_engine_NativeProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     in_ramanujan_rule_engine_NativeProcessor
 * Method:    process
 * Signature: ([BLjava/lang/String;)V
 */
JNIEXPORT jobject JNICALL Java_in_ramanujan_rule_engine_NativeProcessor_process
        (JNIEnv *, jobject, jbyteArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
