
# FROM anapsix/alpine-java

# Pull base image.
FROM ubuntu:16.04

# Install OpenJDK-8
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Fix certificate issues
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME

WORKDIR /
COPY resources/MiddlewareCloudStorageWrite.json Storage.json
COPY resources/MetricPusherCred.json MetricPusherCred.json
COPY resources/pubSubKey.json pubSubKey.json
COPY rest/target/rest-1.0-SNAPSHOT-fat.jar rest-1.0-SNAPSHOT-fat.jar
COPY config/application-config-prod.json config.json
MAINTAINER PSAXENA
EXPOSE 8888:8888/tcp
EXPOSE 8890:8890/tcp
EXPOSE 5005:5005/tcp
EXPOSE 9010:9010/tcp
CMD ["java","-jar","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005", "-Dcom.sun.management.jmxremote", "-Dcom.sun.management.jmxremote.port=9010","-Dcom.sun.management.jmxremote.local.only=false", "-Dcom.sun.management.jmxremote.authenticate=false", "-Dcom.sun.management.jmxremote.ssl=false","rest-1.0-SNAPSHOT-fat.jar","-conf", "config.json"]
