#!/usr/bin/env python3
"""Generate a rich ~50KB English corpus for TinyBERT training."""

shakespeare = (
    "to be or not to be that is the question whether tis nobler in the mind to suffer "
    "the slings and arrows of outrageous fortune or to take arms against a sea of troubles "
    "and by opposing end them to die to sleep no more and by a sleep to say we end "
    "the heartache and the thousand natural shocks that flesh is heir to tis a consummation "
    "devoutly to be wished to die to sleep perchance to dream ay there is the rub "
    "for in that sleep of death what dreams may come when we have shuffled off this mortal coil "
    "must give us pause there is the respect that makes calamity of so long life "
    "for who would bear the whips and scorns of time the oppressors wrong "
    "the proud mans contumely the pangs of despised love the laws delay "
    "the insolence of office and the spurns that patient merit of the unworthy takes "
    "when he himself might his quietus make with a bare bodkin who would fardels bear "
    "to grunt and sweat under a weary life but that the dread of something after death "
    "the undiscovered country from whose bourn no traveler returns puzzles the will "
    "and makes us rather bear those ills we have than fly to others that we know not of "
    "thus conscience does make cowards of us all and thus the native hue of resolution "
    "is sicklied oer with the pale cast of thought and enterprises of great pitch and moment "
    "shall i compare thee to a summers day thou art more lovely and more temperate "
    "rough winds do shake the darling buds of may and summers lease hath all too short a date "
    "sometime too hot the eye of heaven shines and often is his gold complexion dimmed "
    "and every fair from fair sometime declines by chance or natures changing course untrimmed "
    "but thy eternal summer shall not fade nor lose possession of that fair thou owest "
    "nor shall death brag thou wanderest in his shade when in eternal lines to time thou growest "
    "so long as men can breathe or eyes can see so long lives this and this gives life to thee "
    "all the worlds a stage and all the men and women merely players they have their exits "
    "and their entrances and one man in his time plays many parts his acts being seven ages "
    "at first the infant mewling and puking in the nurses arms then the whining schoolboy "
    "with his satchel and shining morning face creeping like snail unwillingly to school "
    "then the lover sighing like furnace with a woeful ballad made to his mistress eyebrow "
    "friends romans countrymen lend me your ears i come to bury caesar not to praise him "
    "the evil that men do lives after them the good is oft interred with their bones "
    "so let it be with caesar the noble brutus hath told you caesar was ambitious "
    "if it were so it was a grievous fault and grievously hath caesar answered it "
    "here under leave of brutus and the rest for brutus is an honourable man "
    "so are they all all honourable men come i to speak in caesars funeral "
    "he was my friend faithful and just to me but brutus says he was ambitious "
    "cowards die many times before their deaths the valiant never taste of death but once "
    "of all the wonders that i yet have heard it seems to me most strange that men should fear "
    "seeing that death a necessary end will come when it will come "
    "what a piece of work is a man how noble in reason how infinite in faculty "
    "in form and moving how express and admirable in action how like an angel "
    "in apprehension how like a god the beauty of the world the paragon of animals "
    "the quality of mercy is not strained it droppeth as the gentle rain from heaven "
    "upon the place beneath it is twice blessed it blesseth him that gives and him that takes "
    "good night good night parting is such sweet sorrow that i shall say good night till it be morrow "
    "what light through yonder window breaks it is the east and juliet is the sun "
    "arise fair sun and kill the envious moon who is already sick and pale with grief "
    "the course of true love never did run smooth love looks not with the eyes but with the mind "
    "and therefore is winged cupid painted blind love is not love which alters when it alteration finds "
)

classics = (
    "it was the best of times it was the worst of times it was the age of wisdom "
    "it was the age of foolishness it was the epoch of belief it was the epoch of incredulity "
    "it was the season of light it was the season of darkness it was the spring of hope "
    "it was the winter of despair we had everything before us we had nothing before us "
    "we were all going direct to heaven we were all going direct the other way "
    "in short the period was so far like the present period that some of its noisiest authorities "
    "insisted on its being received for good or for evil in the superlative degree of comparison "
    "it was a bright cold day in april and the clocks were striking thirteen "
    "happy families are all alike every unhappy family is unhappy in its own way "
    "all animals are equal but some animals are more equal than others "
    "it is a truth universally acknowledged that a single man in possession of a good fortune "
    "must be in want of a wife however little known the feelings or views of such a man may be "
    "on his first entering a neighbourhood this truth is so well fixed in the minds of surrounding families "
    "call me ishmael some years ago never mind how long precisely "
    "having little or no money in my purse and nothing particular to interest me on shore "
    "i thought i would sail about a little and see the watery part of the world "
    "in the beginning god created the heavens and the earth and the earth was without form "
    "and void and darkness was upon the face of the deep and god said let there be light "
    "and there was light and god saw that the light was good and god divided the light from the darkness "
    "the sun also rises and in the morning light all things look different than they did the night before "
    "ask not what your country can do for you ask what you can do for your country "
    "four score and seven years ago our fathers brought forth on this continent a new nation "
    "conceived in liberty and dedicated to the proposition that all men are created equal "
    "we hold these truths to be self evident that all men are created equal "
    "that they are endowed by their creator with certain unalienable rights "
    "that among these are life liberty and the pursuit of happiness "
    "to be prepared for war is one of the most effective means of preserving peace "
    "the only thing we have to fear is fear itself nameless unreasoning unjustified terror "
    "which paralyzes needed efforts to convert retreat into advance "
    "we shall fight on the beaches we shall fight on the landing grounds "
    "we shall fight in the fields and in the streets we shall fight in the hills "
    "we shall never surrender and even if which i do not for a moment believe "
    "this island or a large part of it were subjugated and starving "
    "then our empire beyond the seas armed and guarded by the british fleet "
    "would carry on the struggle until in gods good time the new world "
    "with all its power and might steps forth to the rescue and the liberation of the old "
)

common_patterns = (
    "the the the the the and and and and and that that that have have for for not with "
    "this they from which their about would there been one has more when will make like "
    "time just him know take into year your good some could them see other than then "
    "the question whether tis nobler suffer slings arrows outrageous fortune take arms "
    "against sea troubles opposing end them sleep heartache thousand natural shocks "
    "question whether noble mind suffer slings arrows take arms troubles opposing "
    "sleep heartache shocks flesh heir consummation devoutly wished dream death "
    "the question is whether to be or not to be that is the question that we ask "
    "to be or not to be the question whether tis nobler in the mind to suffer "
    "in the beginning there was the word and the word was good and the word was light "
    "the light shines in the darkness and the darkness has not overcome the light "
    "what is the question what is the answer what is the meaning of it all "
    "the best way to predict the future is to create it the future begins today "
    "whether you think you can or think you cannot you are right about that "
    "success is not final failure is not fatal it is the courage to continue that counts "
    "do not go gentle into that good night rage rage against the dying of the light "
    "the only way to do great work is to love what you do keep looking do not settle "
    "the world is a book and those who do not travel read only one page of that book "
    "a room without books is like a body without a soul not all those who wander are lost "
    "there is no greater agony than bearing an untold story inside you always "
    "water is the driving force of all nature the greatest enemy of knowledge is not ignorance "
    "it is the illusion of knowledge it always seems impossible until it is done "
    "the measure of intelligence is the ability to change and adapt to new situations "
    "imagination is more important than knowledge for knowledge is limited "
    "but imagination encircles the entire world and everything in it "
    "in the middle of every difficulty lies opportunity and the seeds of equivalent benefit "
    "the journey of a thousand miles begins with one step forward into the unknown "
    "silence is not empty it is full of answers if only we would listen carefully "
    "he who has a why to live can bear almost any how knowledge speaks but wisdom listens "
    "well behaved women seldom make history you only live once but if you do it right "
    "be yourself everyone else is already taken you have brains in your head and feet "
    "you can steer yourself any direction you choose a friend is one that knows you "
    "understands where you have been accepts what you have become and still allows growth "
    "not all those who wander are lost the old that is strong does not wither "
    "deep roots are not reached by the frost from the ashes a fire shall be woken "
    "a light from the shadows shall spring renewed shall be blade that was broken "
    "the crownless again shall be king and the lost shall at last be found again "
    "there and back again a hobbit tale by bilbo baggins of the shire "
    "in a hole in the ground there lived a hobbit not a nasty dirty wet hole "
    "nor a dry bare sandy hole but a comfortable hobbit hole with good food and warm fire "
    "a wizard is never late nor is he early he arrives precisely when he means to "
    "all we have to decide is what to do with the time that is given us "
    "the world is indeed full of peril and in it there are many dark places "
    "but still there is much that is fair and though in all lands love is now mingled with grief "
    "it grows perhaps the greater "
    "the the and the and the the and and the the the the and and and the the and "
    "that that the that and that the that and the that that that the and the that "
    "is is it is is it is it the is it is and is it is the is it and is the is "
    "to to to to the to to to to and to to to be to to to the to and to to "
    "be be be be be be be the be be be be be and be be to be be be be be be "
    "in in in in in in in the in in in in and in in in in in in in in in in "
    "of of of of of of of the of of of of and of of of of of of of of of of "
    "a a a a a a a the a a a a a and a a a a a a a a a a a a a a a a a a "
)

pangrams = (
    "The quick brown fox jumps over the lazy dog. "
    "Sphinx of black quartz, judge my vow! How quickly daft jumping zebras vex. "
    "Five boxing wizards jump quickly. Pack my box with five dozen liquor jugs. "
    "The five boxing wizards jump quickly. How vexingly quick daft zebras jump! "
    "We promptly judged antique ivory buckles for the next prize. "
    "Fix problem quickly with galvanized jets. Brown jars prevent liquid from freezing. "
    "abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ 0123456789 "
    "All letters appear here! The five boxing wizards jump so quickly every time. "
    "Sympathizing would fix Quaker objectives. A wizard job quickly pays the fox. "
    "Zephyrs vex bold knight, quaff damp crow. Pack my box with five dozen liquor jugs. "
    "The quick brown fox jumps over the lazy dog. Sphinx of black quartz: judge my vow. "
    "To Be or Not To Be -- that is the Question. Whether 'tis nobler in the Mind. "
    "Suffer the Slings and Arrows of outrageous Fortune, or take Arms against Troubles. "
    "The quick brown fox (version 2): jumps over the lazy dog [again]. "
    "In the beginning was the Word, and the Word was good, and the Word was all things. "
    "The Sun rises in the East and sets in the West; the Moon follows the Sun always. "
    "To be, or not to be: that is the question! To suffer or to act -- that is the choice. "
    "Shakespeare wrote: 'All the world's a stage, and all the men and women merely players.' "
    "Numbers: 1 2 3 4 5 6 7 8 9 0. Letters: A B C D E F G H I J K L M N O P Q R S T U V W X Y Z. "
    "Punctuation matters: commas, periods, quotes, dashes -- all part of writing! "
    "Question: what is the answer? Answer: 42. Question: why? Answer: because it is. "
    "The question is this: to be, or not to be? That is always the question we face. "
    "Hello, World! Hello, World! Hello, World! Testing 1 2 3. Testing A B C. "
    "The quick brown fox. The quick brown fox! The quick brown fox? The quick brown fox: "
)

# Assemble with heavy repetition of key sections
parts = [
    shakespeare * 3,
    classics * 2,
    common_patterns * 3,
    pangrams * 4,
    shakespeare,     # extra pass
    common_patterns, # extra pass
]

corpus = " ".join(parts)

# Keep only printable ASCII (codes 32-126), no newlines
corpus = "".join(c for c in corpus if 32 <= ord(c) <= 126)

print(f"Corpus length: {len(corpus):,} chars")
print(f"Unique chars:  {len(set(corpus))}")
print(f"Sample (first 200): {corpus[:200]}")

outpath = "/Users/pranav/Desktop/ramanujan_oss/ramanujan/ramanujan-test-codes/tinyBert/corpus.txt"
with open(outpath, "w", encoding="ascii") as f:
    f.write(corpus)
print(f"Written to {outpath}")
