@startuml
'https://plantuml.com/sequence-diagram

autonumber

DevConsole -> Middleware: Request
Middleware -> Middleware: check code;\ntranslate to intermediate code
Middleware -> DevConsole: AsyncId

loop async processing done:
    DevConsole -> Middleware: StatusCheck(AsyncId)
    Middleware -> DevConsole: Status
end

@enduml